import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { OperatorRequestError, UUID, readOperatorList } from "./api";
import { controlClass, DateValue, human, Loading, money, Notice, PageHeading, ShortId } from "./shared";
import { useOperatorSession } from "./session";
import type { Endpoint, EndpointMap, Filters, Purchase, Reconciliation, Redemption, Student } from "./types";

type Column<T extends {id:string}>={label:string;render:(item:T)=>React.ReactNode};
interface PageConfig<E extends Endpoint>{endpoint:E;title:string;description:string;columns:Column<EndpointMap[E]>[];filters:FilterSpec[]}
type FilterSpec={key:string;label:string;options?:[string,string][];uuid?:boolean};
const studentFilters:FilterSpec[]=[{key:"eligibilityStatus",label:"Eligibility status",options:[["","All statuses"],["pending","Pending"],["approved","Approved"],["rejected","Rejected"],["suspended","Suspended"]]}];
const studentIdFilter:FilterSpec={key:"studentId",label:"Student ID",uuid:true};
const configs:{[E in Endpoint]:PageConfig<E>}={
 students:{endpoint:"students",title:"Students",description:"Review student eligibility and masked contact details.",filters:studentFilters,columns:[{label:"Student",render:i=><ShortId value={i.id}/>},{label:"Status",render:i=><Status value={i.eligibilityStatus}/>},{label:"Masked email",render:i=>i.maskedEmail??"—"},{label:"Masked phone",render:i=><span className="whitespace-nowrap">{i.maskedPhone??"—"}</span>},{label:"Reviewed",render:i=><DateValue value={i.eligibilityReviewedAt}/>},{label:"Updated",render:i=><DateValue value={i.updatedAt}/>},{label:"Action",render:i=><StudentReviewLink student={i}/>} ]},
 purchases:{endpoint:"purchases",title:"Purchases",description:"View completed Downtown U plan purchases and credit totals.",filters:[{key:"status",label:"Purchase status",options:[["","All statuses"],["paid","Paid"],["partially_refunded","Partially refunded"],["refunded","Refunded"]]},studentIdFilter],columns:[{label:"Purchase",render:i=><ShortId value={i.id}/>},{label:"Student",render:i=><ShortId value={i.studentId}/>},{label:"Plan",render:i=>human(i.planId)},{label:"Status",render:i=><Status value={i.status}/>},{label:"Credits",render:i=><span className="tabular-nums">{i.creditsGranted}</span>},{label:"Amount",render:i=><span className="tabular-nums">{money(i.priceCents)}</span>},{label:"Paid",render:i=><DateValue value={i.paidAt}/>} ]},
 redemptions:{endpoint:"redemptions",title:"Meal activity",description:"View meal credit reservations and completed activity.",filters:[{key:"status",label:"Activity status",options:[["","All statuses"],["reserved","Reserved"],["redeemed","Redeemed"],["reversed","Reversed"],["cancelled","Cancelled"]]},studentIdFilter],columns:[{label:"Activity",render:i=><ShortId value={i.id}/>},{label:"Student",render:i=><ShortId value={i.studentId}/>},{label:"Meal",render:i=>i.mealName},{label:"Status",render:i=><Status value={i.status}/>},{label:"Credits",render:i=><span className="tabular-nums">{i.credits}</span>},{label:"Reserved",render:i=><DateValue value={i.reservedAt}/>},{label:"Completed",render:i=><DateValue value={i.redeemedAt??i.reversedAt}/>} ]},
 reconciliation:{endpoint:"reconciliation",title:"Reconciliation",description:"View payment and kitchen follow-up records.",filters:[{key:"state",label:"Review state",options:[["","All states"],["needs_review","Needs review"],["resolved","Resolved"]]},{key:"category",label:"Category",options:[["","All categories"],["payment_follow_up","Payment follow-up"],["kitchen_follow_up","Kitchen follow-up"]]},studentIdFilter],columns:[{label:"Record",render:i=><ShortId value={i.id}/>},{label:"Student",render:i=><ShortId value={i.studentId}/>},{label:"Category",render:i=>human(i.category)},{label:"State",render:i=><Status value={i.state}/>},{label:"Opened",render:i=><DateValue value={i.openedAt}/>},{label:"Resolved",render:i=><DateValue value={i.resolvedAt}/>} ]},
};
function Status({value}:{value:string}){return <span className="inline-flex items-center gap-2 font-semibold"><span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-[#725f31]"/>{human(value)}</span>;}
function StudentReviewLink({student}:{student:Student}){const {session}=useOperatorSession();return !student.deletedAt&&session.operator.roles.includes("eligibility_reviewer")?<Link className="inline-flex min-h-11 items-center font-semibold underline underline-offset-4" to={`/downtown-u/operator/students/${student.id}`}>Review student</Link>:null;}
export function StudentsPage(){return <ListPage config={configs.students}/>;} export function PurchasesPage(){return <ListPage config={configs.purchases}/>;} export function RedemptionsPage(){return <ListPage config={configs.redemptions}/>;} export function ReconciliationPage(){return <ListPage config={configs.reconciliation}/>;}
function ListPage<E extends Endpoint>({config}:{config:PageConfig<E>}){
 const {endSession}=useOperatorSession(); const [values,setValues]=useState<Record<string,string>>({}); const [cursor,setCursor]=useState<string|null>(null); const [history,setHistory]=useState<(string|null)[]>([]);
 const invalid=config.filters.some(filter=>filter.uuid&&values[filter.key]!==undefined&&values[filter.key]!==""&&!UUID.test(values[filter.key]));
 const filters=useMemo(()=>Object.fromEntries(Object.entries(values).filter(([,value])=>value!==""&&!invalid)),[values,invalid]);
 const queryFilters=useMemo(()=>({...filters,cursor}),[filters,cursor]);
 const query=useQuery({queryKey:["operator",config.endpoint,queryFilters],queryFn:()=>readOperatorList(config.endpoint,filters,cursor),enabled:!invalid,retry:false});
 useEffect(()=>{if(query.error instanceof OperatorRequestError&&query.error.kind==="session")endSession();},[query.error,endSession]);
 const change=(key:string,value:string)=>{setValues(current=>({...current,[key]:value.trim()}));setCursor(null);setHistory([]);};
 return <><PageHeading description={config.description}>{config.title}</PageHeading><Filters specs={config.filters} values={values} change={change} invalid={invalid}/>{!invalid&&query.isPending&&<Loading/>}{query.isError&&!(query.error instanceof OperatorRequestError&&query.error.kind==="session")&&<Notice role="alert" title="Records unavailable" retry={()=>void query.refetch()}>We couldn’t load these records. Try again.</Notice>}{query.data&&query.data.items.length===0&&<Notice title={Object.values(filters).some(Boolean)?"No matching records":"No records yet"}>{Object.values(filters).some(Boolean)?"Try changing or clearing the filters.":"There are no records to show."}</Notice>}{query.data&&query.data.items.length>0&&<Records label={config.title} columns={config.columns} items={query.data.items}/>} {query.data&&<div className="mt-6 flex items-center justify-between border-t border-[#d1c6b1] pt-4"><button type="button" className="min-h-11 rounded-md border border-[#837b6b] bg-[#fffaf0] px-4 text-sm font-semibold disabled:opacity-45" disabled={!history.length} aria-label="Previous page" onClick={()=>{const previous=[...history];const target=previous.pop()??null;setHistory(previous);setCursor(target);}}>Previous</button><span className="text-xs text-[#5c574d]" aria-live="polite">Page {history.length+1}</span><button type="button" className="min-h-11 rounded-md border border-[#837b6b] bg-[#fffaf0] px-4 text-sm font-semibold disabled:opacity-45" disabled={!query.data.nextCursor} aria-label="Next page" onClick={()=>{setHistory(old=>[...old,cursor]);setCursor(query.data.nextCursor);}}>Next</button></div>}</>;
}
function Filters({specs,values,change,invalid}:{specs:FilterSpec[];values:Record<string,string>;change:(key:string,value:string)=>void;invalid:boolean}){return <section aria-label="Filters" className="mb-6 grid gap-4 border-b border-[#d1c6b1] pb-6 sm:grid-cols-2 lg:grid-cols-3">{specs.map(spec=><div key={spec.key}><label htmlFor={`filter-${spec.key}`} className="mb-2 block text-sm font-semibold">{spec.label}</label>{spec.options?<select id={`filter-${spec.key}`} className={controlClass} value={values[spec.key]??""} onChange={e=>change(spec.key,e.target.value)}>{spec.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input id={`filter-${spec.key}`} className={controlClass} value={values[spec.key]??""} onChange={e=>change(spec.key,e.target.value)} placeholder="Enter student ID" autoComplete="off" aria-invalid={invalid||undefined} aria-describedby={invalid?"student-id-error":undefined}/>} {spec.uuid&&invalid&&<p id="student-id-error" role="alert" className="mt-2 text-sm font-semibold text-[#8d2e25]">Enter a valid student ID.</p>}</div>)}</section>;}
function Records<T extends {id:string}>({label,columns,items}:{label:string;columns:Column<T>[];items:T[]}){return <><div className="hidden md:block"><table aria-label={label} className="w-full table-fixed border-collapse text-left text-sm"><thead><tr className="border-b-2 border-[#837b6b]">{columns.map(column=><th key={column.label} scope="col" className="px-2 py-3 font-bold">{column.label}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b border-[#d1c6b1] align-top">{columns.map(column=><td key={column.label} className="break-words px-2 py-4 leading-5">{column.render(item)}</td>)}</tr>)}</tbody></table></div><ul aria-label={`${label} mobile records`} className="space-y-4 md:hidden">{items.map(item=><li key={item.id} className="border border-[#c2b7a2] bg-[#fffaf0] p-4"><dl className="grid grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)] gap-x-3 gap-y-3">{columns.map(column=><div className="contents" key={column.label}><dt className="text-xs font-bold uppercase tracking-wide text-[#665f53]">{column.label}</dt><dd className="min-w-0 break-words text-sm">{column.render(item)}</dd></div>)}</dl></li>)}</ul></>;}
