import { useLayoutEffect, useRef } from "react";
import type { ReactNode } from "react";

const labels: Record<string,string> = { pending:"Pending",approved:"Approved",rejected:"Rejected",suspended:"Suspended",paid:"Paid",partially_refunded:"Partially refunded",refunded:"Refunded",reserved:"Reserved",redeemed:"Redeemed",reversed:"Reversed",cancelled:"Cancelled",needs_review:"Needs review",resolved:"Resolved",payment_follow_up:"Payment follow-up",kitchen_follow_up:"Kitchen follow-up", "flex-5":"Flex 5", "scholar-10":"Scholar 10", "resident-20":"Resident 20", "semester-40":"Semester 40" };
// eslint-disable-next-line react-refresh/only-export-components
export function human(value:string){return labels[value]??value;}
// eslint-disable-next-line react-refresh/only-export-components
export function money(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);}
export function DateValue({value}:{value?:string}) { if(!value)return <span aria-label="Not available">—</span>; return <time dateTime={value} title={value}>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}</time>; }
export function ShortId({value}:{value:string}) { return <span className="font-mono text-xs tabular-nums" title={value} aria-label={value}>{value.slice(0,8)}…</span>; }
export function PageHeading({children,description}:{children:ReactNode;description:string}) { const ref=useRef<HTMLHeadingElement>(null); useLayoutEffect(()=>ref.current?.focus(),[]); return <header className="mb-6 border-b border-[#d1c6b1] pb-5"><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-[#725f31]">Downtown U operations</p><h1 ref={ref} tabIndex={-1} className="font-display text-3xl font-semibold tracking-tight text-[#1b1a17] outline-none sm:text-4xl">{children}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#5c574d]">{description}</p></header>; }
export function Loading() { return <div role="status" aria-live="polite" className="space-y-3"><span className="sr-only">Loading records</span>{[1,2,3].map(i=><div key={i} aria-hidden="true" className="h-14 animate-pulse rounded-md bg-[#ded5c3] motion-reduce:animate-none" />)}</div>; }
export function Notice({title,children,retry,role}:{title:string;children:ReactNode;retry?:()=>void;role?:"alert"}) { return <section role={role} className="border-l-4 border-[#8b743d] bg-[#fffaf0] p-5"><h2 className="font-body text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-[#5c574d]">{children}</p>{retry&&<button type="button" onClick={retry} className="mt-4 min-h-11 rounded-md bg-[#1b1a17] px-4 text-sm font-semibold text-[#fff9eb] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8b743d] focus-visible:ring-offset-2">Try again</button>}</section>; }
export const controlClass="min-h-11 w-full rounded-md border border-[#837b6b] bg-[#fffaf0] px-3 text-base text-[#1b1a17] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8b743d] sm:text-sm";
