import { beforeEach, describe, expect, it, vi } from "vitest";

import { config, createExpireReservationsHandler } from "../jobs/expire-reservations";
import type { NodePortalRequest, NodePortalResponse } from "../student-portal-handler";

const secret=Buffer.from(Array.from({length:32},(_,i)=>i+1)).toString("base64url");
const pool={tag:"runtime-pool"};
const boundaries={getPool:vi.fn(()=>pool),run:vi.fn().mockResolvedValue(0),compare:vi.fn((a:Buffer,b:Buffer)=>a.equals(b))};
function request(chunks:unknown[]=[],properties:Record<string,unknown>={}):NodePortalRequest{return{method:"POST",headers:{authorization:`Bearer ${secret}`},...properties,async *[Symbol.asyncIterator](){for(const chunk of chunks)yield chunk}} as NodePortalRequest}
function response(){const headers:Record<string,string>={};let status=0;let body:unknown;const value:NodePortalResponse={setHeader(n,v){headers[n]=v},status(code){status=code;return{json(v){body=v}}}};return{value,headers,get status(){return status},get body(){return body}}}
function create(env:NodeJS.ProcessEnv={DOWNTOWN_U_PORTAL_ENABLED:"1",DOWNTOWN_U_JOBS_DATABASE_URL:"postgres://runtime",CRON_SECRET:secret}){return createExpireReservationsHandler(env,boundaries as never)}
beforeEach(()=>{vi.clearAllMocks();boundaries.getPool.mockReturnValue(pool);boundaries.run.mockResolvedValue(0);boundaries.compare.mockImplementation((a,b)=>a.equals(b))});

describe("reservation expiry job HTTP boundary",()=>{
 it("accepts exact GET for Vercel cron and exact POST for manual scheduling",async()=>{for(const method of ["GET","POST"]){const res=response();await create()(request([],{method}),res.value);expect(res.status).toBe(202)}for(const method of ["get","post",undefined]){const res=response();await create()(request([],{method}),res.value);expect(res.status).toBe(405);expect(res.headers).toMatchObject({"Cache-Control":"private, no-store, max-age=0","Content-Security-Policy":"default-src 'none'; frame-ancestors 'none'","Referrer-Policy":"no-referrer","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY"})}});
 it("requires a canonical strong 43-character base64url secret decoded to 32 non-placeholder bytes",async()=>{for(const candidate of [undefined,"short","A".repeat(43),secret+"x",secret.slice(0,-1)+"="]){const res=response();await create({DOWNTOWN_U_PORTAL_ENABLED:"1",DOWNTOWN_U_JOBS_DATABASE_URL:"postgres://runtime",CRON_SECRET:candidate})(request([],{headers:{authorization:`Bearer ${candidate}`}}),res.value);expect(res.status).toBe(401)}expect(boundaries.run).not.toHaveBeenCalled()});
 it("uses CRON_SECRET preferentially and falls back only when it is absent",async()=>{const fallback=Buffer.from(Array.from({length:32},(_,i)=>i+51)).toString("base64url");for(const [env,token,status] of [[{DOWNTOWN_U_PORTAL_ENABLED:"1",DOWNTOWN_U_JOBS_DATABASE_URL:"postgres://runtime",CRON_SECRET:secret,DOWNTOWN_U_JOBS_SECRET:fallback},secret,202],[{DOWNTOWN_U_PORTAL_ENABLED:"1",DOWNTOWN_U_JOBS_DATABASE_URL:"postgres://runtime",DOWNTOWN_U_JOBS_SECRET:fallback},fallback,202],[{DOWNTOWN_U_PORTAL_ENABLED:"1",DOWNTOWN_U_JOBS_DATABASE_URL:"postgres://runtime",CRON_SECRET:"invalid",DOWNTOWN_U_JOBS_SECRET:fallback},fallback,401]] as const){const res=response();await create(env)(request([],{method:"GET",headers:{authorization:`Bearer ${token}`}}),res.value);expect(res.status).toBe(status)}});
 it("runs fixed-buffer comparison even for a well-formed unequal token",async()=>{const other=Buffer.from(Array.from({length:32},(_,i)=>i+71)).toString("base64url");const res=response();await create()(request([],{headers:{authorization:`Bearer ${other}`}}),res.value);expect(res.status).toBe(401);expect(boundaries.compare).toHaveBeenCalledWith(expect.objectContaining({length:32}),expect.objectContaining({length:32}))});
 it("rejects missing, malformed, accessor, array, and duplicate Authorization without invoking accessors",async()=>{const getter=vi.fn(()=>`Bearer ${secret}`);const accessor={};Object.defineProperty(accessor,"authorization",{enumerable:true,get:getter});for(const properties of [{headers:{}},{headers:{authorization:[`Bearer ${secret}`]}},{headers:accessor},{headers:{authorization:`Bearer ${secret}`},rawHeaders:["Authorization",`Bearer ${secret}`,"authorization",`Bearer ${secret}`]},{headers:{authorization:`Bearer ${secret}`},rawHeaders:["Authorization"]}]){const res=response();await create()(request([],properties),res.value);expect(res.status).toBe(401)}expect(getter).not.toHaveBeenCalled();expect(boundaries.run).not.toHaveBeenCalled()});
 it("does not invoke a request headers accessor",async()=>{const req=request();const getter=vi.fn(()=>({authorization:`Bearer ${secret}`}));Object.defineProperty(req,"headers",{enumerable:true,get:getter});const res=response();await create()(req,res.value);expect(res.status).toBe(401);expect(getter).not.toHaveBeenCalled()});
 it("rejects Origin and every content or transfer framing header including malformed values",async()=>{for(const extra of [{origin:"https://app.test"},{"content-type":"application/json"},{"transfer-encoding":"chunked"},{"content-length":"1"},{"content-length":["0"]},{"Content-Length":"0","content-length":"0"}]){const res=response();await create()(request([],{headers:{authorization:`Bearer ${secret}`,...extra}}),res.value);expect(res.status).toBe(400)}expect(boundaries.run).not.toHaveBeenCalled()});
 it("allows absent or exact zero Content-Length and rejects nonempty/non-byte raw bodies",async()=>{for(const headers of [{authorization:`Bearer ${secret}`},{authorization:`Bearer ${secret}`,"content-length":"0"}]){const res=response();await create()(request([],{headers}),res.value);expect(res.status).toBe(202)}for(const chunks of [[Buffer.from("x")],["x"]]){const res=response();await create()(request(chunks),res.value);expect(res.status).toBe(400)}});
 it("rejects preparsed, ended, and accessor body state without evaluating accessors",async()=>{const getter=vi.fn(()=>{throw new Error("must not run")});const cases=[request([],{body:{}}),request([],{readableEnded:true}),request()];Object.defineProperty(cases[2],"body",{get:getter});for(const req of cases){const res=response();await create()(req,res.value);expect(res.status).toBe(400)}expect(getter).not.toHaveBeenCalled()});
 it("passes the runtime pool and bounded limit, and never returns the secret",async()=>{boundaries.run.mockResolvedValueOnce(100);const res=response();await create()(request(),res.value);expect({status:res.status,body:res.body}).toEqual({status:202,body:{accepted:true}});expect(boundaries.getPool).toHaveBeenCalledWith("postgres://runtime");expect(boundaries.run).toHaveBeenCalledWith(pool,100);expect(JSON.stringify({headers:res.headers,body:res.body})).not.toContain(secret)});
 it("requires the capability boundary to return exactly one integer in range",async()=>{for(const value of [-1,101,1.5,Number.NaN,undefined,"1"]){boundaries.run.mockResolvedValueOnce(value as never);const res=response();await create()(request(),res.value);expect({status:res.status,body:res.body}).toEqual({status:503,body:{error:"unavailable"}})}});
 it("fails closed behind the exact deployment flag before endpoint-specific handling",async()=>{for(const enabled of [undefined,"0","true","01"]){const res=response();await create({DOWNTOWN_U_PORTAL_ENABLED:enabled,CRON_SECRET:secret,DOWNTOWN_U_JOBS_DATABASE_URL:"postgres://runtime"})(request([],{method:"DELETE",headers:{}}),res.value);expect({status:res.status,body:res.body}).toEqual({status:503,body:{error:"unavailable"}})}expect(boundaries.run).not.toHaveBeenCalled()});
 it("maps missing DB, pool failures, and capability failures to generic 503",async()=>{const scenarios=[async()=>create({DOWNTOWN_U_PORTAL_ENABLED:"1",CRON_SECRET:secret}),async()=>{boundaries.getPool.mockImplementationOnce(()=>{throw new Error("db pii")});return create()},async()=>{boundaries.run.mockRejectedValueOnce(new Error("student@example db cause"));return create()}];for(const make of scenarios){const res=response();const handler=await make();await handler(request(),res.value);expect({status:res.status,body:res.body}).toEqual({status:503,body:{error:"unavailable"}});expect(JSON.stringify(res.body)).not.toMatch(/student|db|secret/)}});
 it("logs only generic status and count, never credentials, PII, or failure causes",async()=>{const info=vi.spyOn(console,"info").mockImplementation(()=>{});const error=vi.spyOn(console,"error").mockImplementation(()=>{});boundaries.run.mockResolvedValueOnce(7);let res=response();await create()(request(),res.value);boundaries.run.mockRejectedValueOnce(new Error(`student@example.test ${secret}`));res=response();await create()(request(),res.value);const output=JSON.stringify([...info.mock.calls,...error.mock.calls]);expect(output).toContain("7");expect(output).toContain("503");expect(output).not.toMatch(/student@example|database|cause/);expect(output).not.toContain(secret);info.mockRestore();error.mockRestore()});
 it("exports raw-body-parser-disabled configuration",()=>{expect(config).toEqual({api:{bodyParser:false}})});
});
