import { beforeEach,describe,expect,it,vi } from "vitest";import { config,createKitchenOrdersHandler } from "../jobs/process-kitchen-orders";import type { NodePortalRequest,NodePortalResponse } from "../student-portal-handler";
const secret=Buffer.from(Array.from({length:32},(_,i)=>i+1)).toString("base64url"),pool={},square={locationId:"LPPWSSV03BHK8"};
const b={getPool:vi.fn(()=>pool),square:vi.fn(()=>square),run:vi.fn().mockResolvedValue({claimed:0,completed:0,deferred:0}),compare:vi.fn((a:Buffer,c:Buffer)=>a.equals(c))};
function req(p:Record<string,unknown>={}):NodePortalRequest{return{method:"GET",headers:{authorization:`Bearer ${secret}`},...p,async *[Symbol.asyncIterator](){}} as NodePortalRequest}function res(){let status=0,body:unknown;const value={setHeader:vi.fn(),status(s:number){status=s;return{json(x:unknown){body=x}}}} as unknown as NodePortalResponse;return{value,get status(){return status},get body(){return body}}}const env={DOWNTOWN_U_PORTAL_ENABLED:"1",DOWNTOWN_U_KITCHEN_ORDERS_ENABLED:"1",DOWNTOWN_U_KITCHEN_DATABASE_URL:"postgres://kitchen",CRON_SECRET:secret,SQUARE_ACCESS_TOKEN:"token",SQUARE_API_VERSION:"2026-01-22",SQUARE_LOCATION_ID:"LPPWSSV03BHK8"};
beforeEach(()=>{vi.clearAllMocks();b.getPool.mockReturnValue(pool);b.square.mockReturnValue(square);b.run.mockResolvedValue({claimed:0,completed:0,deferred:0});b.compare.mockImplementation((a,c)=>a.equals(c))});
describe("kitchen cron API",()=>{
 it("accepts authenticated empty GET/POST and returns no operational detail",async()=>{for(const method of ["GET","POST"]){const r=res();await createKitchenOrdersHandler(env,b as never)(req({method}),r.value);expect({status:r.status,body:r.body}).toEqual({status:202,body:{accepted:true}})}expect(b.getPool).toHaveBeenCalledWith("postgres://kitchen")});
 it("fails closed on either gate, auth, bodies, configuration and wrong location",async()=>{for(const patch of [{DOWNTOWN_U_PORTAL_ENABLED:"0"},{DOWNTOWN_U_KITCHEN_ORDERS_ENABLED:"0"},{DOWNTOWN_U_KITCHEN_DATABASE_URL:undefined}]){const r=res();await createKitchenOrdersHandler({...env,...patch},b as never)(req(),r.value);expect(r.status).toBe(503)}let r=res();await createKitchenOrdersHandler(env,b as never)(req({headers:{}}),r.value);expect(r.status).toBe(401);r=res();await createKitchenOrdersHandler(env,b as never)(req({body:{}}),r.value);expect(r.status).toBe(400);b.square.mockReturnValueOnce({locationId:"OTHER"});r=res();await createKitchenOrdersHandler(env,b as never)(req(),r.value);expect(r.status).toBe(503)});
 it("logs bounded aggregate completion/defer outcomes and returns 503 when persistence cannot be observed",async()=>{b.run.mockResolvedValueOnce({claimed:3,completed:2,deferred:1});let r=res();await createKitchenOrdersHandler(env,b as never)(req(),r.value);expect(r.status).toBe(202);b.run.mockResolvedValueOnce({claimed:2,completed:2,deferred:1});r=res();await createKitchenOrdersHandler(env,b as never)(req(),r.value);expect(r.status).toBe(503);b.run.mockRejectedValueOnce(new Error("database unavailable"));r=res();await createKitchenOrdersHandler(env,b as never)(req(),r.value);expect(r.status).toBe(503)});
 it("requires the dedicated CRON_SECRET and never accepts the general jobs fallback",async()=>{const r=res();await createKitchenOrdersHandler({...env,CRON_SECRET:undefined,DOWNTOWN_U_JOBS_SECRET:secret},b as never)(req(),r.value);expect(r.status).toBe(401);expect(b.run).not.toHaveBeenCalled()});
 it("supports only exact methods, pins bounded execution and disables body parsing",async()=>{for(const method of ["DELETE","get",undefined]){const r=res();await createKitchenOrdersHandler(env,b as never)(req({method}),r.value);expect(r.status).toBe(405)}expect(config).toEqual({api:{bodyParser:false},maxDuration:30})});
});
