import { beforeEach, describe, expect, it, vi } from "vitest";
import { createNodeStudentPortalHandler, createProductionStudentPortalHandler, portalRawJsonConfig, type NodePortalRequest, type NodePortalResponse } from "../student-portal-handler";
import { STUDENT_PORTAL_SECURITY_HEADERS, type PortalEndpoint, type PortalResponse } from "../../../server/downtown-u/student-portal";

const origin="https://app.example.test";
function request(chunks:unknown[]=[],properties:Record<string,unknown>={}):NodePortalRequest {return{method:"POST",headers:{origin,"content-type":"application/json"},...properties,async *[Symbol.asyncIterator](){for(const chunk of chunks)yield chunk}} as NodePortalRequest}
function response(){const headers:Record<string,string>={};let status=0;let body:unknown;let ended=false;const value:NodePortalResponse={setHeader(name,v){headers[name]=v},status(code){status=code;return{json(input){body=input},end(){ended=true}}}};return{value,headers,get status(){return status},get body(){return body},get ended(){return ended}}}
const ok=(status=200,body:unknown={ok:true}):PortalResponse=>({status,body,headers:{...STUDENT_PORTAL_SECURITY_HEADERS}});

beforeEach(()=>vi.clearAllMocks());
describe("student portal Node adapter",()=>{
 it("rejects duplicate raw Cookie lines with complete security and same-origin CORS headers",async()=>{const core=vi.fn();const res=response();await createNodeStudentPortalHandler("me",core as never,origin)(request([],{method:"GET",headers:{origin,cookie:"x"},rawHeaders:["Cookie","x","Cookie","y"]}),res.value);expect({status:res.status,body:res.body}).toEqual({status:401,body:{error:"unauthorized"}});expect(res.headers).toMatchObject({...STUDENT_PORTAL_SECURITY_HEADERS,"Access-Control-Allow-Origin":origin,Vary:"Origin","Content-Type":"application/json; charset=utf-8"});expect(core).not.toHaveBeenCalled()});
 it("treats malformed rawHeaders as unauthorized without consulting accessors",async()=>{const core=vi.fn();for(const rawHeaders of [["Cookie"],["Cookie",1],"bad"]){const res=response();await createNodeStudentPortalHandler("me",core as never)(request([],{method:"GET",headers:{cookie:"x"},rawHeaders}),res.value);expect(res.status).toBe(401)}expect(core).not.toHaveBeenCalled()});
 it("rejects preparsed, ended, and accessor body state without evaluating accessors",async()=>{const core=vi.fn();const getter=vi.fn(()=>{throw new Error("must not run")});const cases=[request([],{body:{}}),request([],{readableEnded:true}),request()];Object.defineProperty(cases[2],"body",{enumerable:true,get:getter});for(const req of cases){const res=response();await createNodeStudentPortalHandler("logout",core as never,origin)(req,res.value);expect(res.status).toBe(400);expect(res.headers).toMatchObject(STUDENT_PORTAL_SECURITY_HEADERS)}expect(getter).not.toHaveBeenCalled();expect(core).not.toHaveBeenCalled()});
 it("rejects malformed JSON and fatal UTF-8 before the core",async()=>{const core=vi.fn();for(const bytes of [Buffer.from("{"),Buffer.from([0xc3,0x28])]){const res=response();await createNodeStudentPortalHandler("logout",core as never)(request([bytes]),res.value);expect(res.status).toBe(400)}expect(core).not.toHaveBeenCalled()});
 it("rejects non-byte chunks and destroys an over-8KiB stream",async()=>{const core=vi.fn();const destroy=vi.fn();for(const chunks of [["text"],[Buffer.alloc(8193)]]){const res=response();await createNodeStudentPortalHandler("logout",core as never)(request(chunks,{destroy}),res.value);expect(res.status).toBe(400)}expect(destroy).toHaveBeenCalled();expect(core).not.toHaveBeenCalled()});
 it("rejects raw read bodies and returns exact 405 before consuming mutation input",async()=>{const core=vi.fn();const readRes=response();await createNodeStudentPortalHandler("me",core as never)(request([Buffer.from("x")],{method:"GET",headers:{}}),readRes.value);expect(readRes.status).toBe(400);const methodRes=response();await createNodeStudentPortalHandler("logout",core as never)(request([Buffer.from("not json")],{method:"GET"}),methodRes.value);expect(methodRes.status).toBe(405);expect(methodRes.headers.Allow).toBe("POST");expect(core).not.toHaveBeenCalled()});
 it("parses only raw JSON and forwards descriptor-safe route parameters",async()=>{const core=vi.fn().mockResolvedValue(ok(201));const res=response();await createNodeStudentPortalHandler("reservation-cancel",core as never)(request([Buffer.from('{"idempotencyKey":"CCCCCCCCCCCCCCCC"}')],{query:{id:"22222222-2222-4222-8222-222222222222"}}),res.value);expect(res.status).toBe(201);expect(core).toHaveBeenCalledWith(expect.objectContaining({body:{idempotencyKey:"CCCCCCCCCCCCCCCC"},reservationId:"22222222-2222-4222-8222-222222222222"}))});
 it("does not invoke query accessors and marks inherited, accessor, symbol, and duplicate-array values invalid",async()=>{const core=vi.fn().mockResolvedValue(ok());const getter=vi.fn(()=>"1");const accessor={};Object.defineProperty(accessor,"limit",{enumerable:true,get:getter});const symbol={limit:"1"};Object.defineProperty(symbol,Symbol("x"),{value:"x"});for(const query of [Object.create({limit:"1"}),accessor,symbol,{limit:["1","2"]}]){const res=response();await createNodeStudentPortalHandler("purchases",core as never)(request([],{method:"GET",headers:{},query}),res.value)}expect(getter).not.toHaveBeenCalled();expect(core.mock.calls.map(call=>call[0].query)).toEqual([{invalid:"1"},{invalid:"1"},{invalid:"1"},{limit:["1","2"]}])});
 it("sends no JSON body for a 204",async()=>{const core=vi.fn().mockResolvedValue({status:204,headers:STUDENT_PORTAL_SECURITY_HEADERS});const res=response();await createNodeStudentPortalHandler("logout",core as never)(request([Buffer.from("{}")]),res.value);expect(res.status).toBe(204);expect(res.ended).toBe(true);expect(res.body).toBeUndefined()});
});

describe("production student portal composition",()=>{
 const auth={validateSession:vi.fn(),revokeSession:vi.fn()};const store={me:vi.fn(),meals:vi.fn(),purchases:vi.fn(),reservations:vi.fn(),reserve:vi.fn(),reverse:vi.fn()};const pool={};const boundaries={getPool:vi.fn(()=>pool),auth:vi.fn(()=>auth),store:vi.fn(()=>store)};
 const env={DOWNTOWN_U_PORTAL_ENABLED:"1",DATABASE_URL:"postgres://runtime",DOWNTOWN_U_PUBLIC_APP_ORIGIN:origin,DOWNTOWN_U_AUTH_SECRET:Buffer.from(Array.from({length:32},(_,i)=>i+1)).toString("base64url")};
 it("initializes every endpoint when the exact feature flag and server configuration are present",async()=>{for(const endpoint of ["me","meals","purchases","reservations","reservation-cancel","logout"] as PortalEndpoint[]){const res=response();await createProductionStudentPortalHandler(endpoint,env,boundaries as never)(request([],{method:"GET",headers:{}}),res.value);expect(res.status).not.toBe(503)}expect(boundaries.getPool).toHaveBeenCalledTimes(6)});
 it("fails missing configuration closed with exact generic 503 and complete headers",async()=>{vi.clearAllMocks();for(const missing of ["DATABASE_URL","DOWNTOWN_U_PUBLIC_APP_ORIGIN","DOWNTOWN_U_AUTH_SECRET"] as const){const broken={...env};delete (broken as Partial<typeof env>)[missing];const res=response();await createProductionStudentPortalHandler("me",broken,boundaries as never)(request([],{method:"GET",headers:{origin}}),res.value);expect({status:res.status,body:res.body}).toEqual({status:503,body:{error:"unavailable"}});expect(res.headers).toMatchObject(STUDENT_PORTAL_SECURITY_HEADERS);if(missing!=="DOWNTOWN_U_PUBLIC_APP_ORIGIN")expect(res.headers["Access-Control-Allow-Origin"]).toBe(origin)}expect(boundaries.getPool).not.toHaveBeenCalled()});
 it("fails every production endpoint closed when the feature flag is absent or not exact 1",async()=>{for(const enabled of [undefined,"0","true","01"]){for(const endpoint of ["me","meals","purchases","reservations","reservation-cancel","logout"] as PortalEndpoint[]){const broken={...env,DOWNTOWN_U_PORTAL_ENABLED:enabled};const res=response();await createProductionStudentPortalHandler(endpoint,broken,boundaries as never)(request([],{method:"INVALID",headers:{}}),res.value);expect({status:res.status,body:res.body}).toEqual({status:503,body:{error:"unavailable"}})}}expect(boundaries.getPool).not.toHaveBeenCalled()});
 it("exports the shared raw JSON route config",()=>{expect(portalRawJsonConfig).toEqual({api:{bodyParser:false}})});
 it("has every portal route export the shared raw JSON config",async()=>{const modules=await Promise.all([import("../me"),import("../meals"),import("../purchases"),import("../reservations"),import("../reservations/[id]/cancel"),import("../logout")]);for(const route of modules)expect(route.config).toBe(portalRawJsonConfig)});
});
