import { describe, expect, it, vi } from "vitest";
import { createCheckoutService, DOWNTOWN_U_LOCATION_ID, type CheckoutAttempt, type CheckoutStore } from "../checkout";
import { SquareApiError, type SquareCheckoutClient, type SquareResource } from "../square-client";

const variation = { "flex-5":"VAR5", "scholar-10":"VAR10", "resident-20":"VAR20", "semester-40":"VAR40" } as const;
class MemoryStore implements CheckoutStore {
  value:CheckoutAttempt={id:"11111111-1111-4111-8111-111111111111",idempotencyKey:"abcdefghijklmnop",planId:"flex-5",normalizedEmail:"student@example.edu",state:"started"};
  begin=vi.fn(async()=>this.value); recordOrder=vi.fn(async(_id:string,id:string)=>(this.value={...this.value,squareOrderId:id,state:"order_created"}));
  recordPayment=vi.fn(async(_id:string,id:string)=>(this.value={...this.value,squarePaymentId:id,state:"payment_created"}));
  transition=vi.fn(async(_id:string,state:"paid"|"operator_review"|"failed")=>(this.value={...this.value,state}));
  readPublic=vi.fn(async()=>({state:this.value.state}));
}
function resources(){const order={id:"ORDER_1",location_id:DOWNTOWN_U_LOCATION_ID,reference_id:"du:11111111-1111-4111-8111-111111111111",state:"OPEN",total_money:{amount:6000,currency:"USD"},line_items:[{catalog_object_id:"VAR5",quantity:"1",base_price_money:{amount:6000,currency:"USD"},total_money:{amount:6000,currency:"USD"}}]};const payment={id:"PAY_1",order_id:"ORDER_1",status:"COMPLETED",location_id:DOWNTOWN_U_LOCATION_ID,reference_id:"du:11111111-1111-4111-8111-111111111111",buyer_email_address:"student@example.edu",amount_money:{amount:6000,currency:"USD"}};return {order,payment};}
function setup(mutate?:(r:{order:SquareResource;payment:SquareResource})=>void){const store=new MemoryStore();const r=resources();mutate?.(r);const client:SquareCheckoutClient={locationId:DOWNTOWN_U_LOCATION_ID,createOrder:vi.fn(async()=>r.order),createPayment:vi.fn(async()=>r.payment),getOrder:vi.fn(async()=>r.order),getPayment:vi.fn(async()=>r.payment),getRefund:vi.fn()};return {store,client,service:createCheckoutService({store,client,locationId:DOWNTOWN_U_LOCATION_ID,catalogVariationIds:variation})};}
const input={planId:"flex-5",sourceId:"cnon:test_token",email:" Student@Example.edu ",eligibilityConfirmed:true,idempotencyKey:"abcdefghijklmnop",requestActor:Buffer.alloc(32,1)};
describe("embedded Downtown U checkout",()=>{
 it("persists before provider calls and sends only server-owned economics",async()=>{const {service,client,store}=setup();await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"paid"});expect(store.begin.mock.invocationCallOrder[0]).toBeLessThan(vi.mocked(client.createOrder).mock.invocationCallOrder[0]);expect(client.createOrder).toHaveBeenCalledWith({idempotency_key:expect.stringMatching(/^o_[a-f0-9]{32}$/),order:{location_id:DOWNTOWN_U_LOCATION_ID,reference_id:`du:${store.value.id}`,line_items:[{catalog_object_id:"VAR5",quantity:"1",base_price_money:{amount:6000,currency:"USD"}}]}});expect(client.createPayment).toHaveBeenCalledWith({idempotency_key:expect.stringMatching(/^p_[a-f0-9]{32}$/),source_id:"cnon:test_token",order_id:"ORDER_1",amount_money:{amount:6000,currency:"USD"},location_id:DOWNTOWN_U_LOCATION_ID,autocomplete:true,buyer_email_address:"student@example.edu",reference_id:`du:${store.value.id}`});});
 it.each(["amount","email","catalog","reference"])("returns stable operator review and refuses paid state on %s drift",async(kind)=>{const {service,store}=setup(r=>{if(kind==="amount")r.payment.amount_money={amount:1,currency:"USD"};if(kind==="email")r.payment.buyer_email_address="other@example.edu";if(kind==="catalog")(r.order.line_items as SquareResource[])[0].catalog_object_id="OTHER";if(kind==="reference")r.order.reference_id="other";});await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"operator_review"});expect(store.value.state).toBe("operator_review");});
 it.each([{...input,eligibilityConfirmed:false},{...input,planId:"unknown"},{...input,sourceId:"bad token"},{...input,email:"bad"}])("rejects malformed canonical input before persistence",async(bad)=>{const {service,store,client}=setup();await expect(service.checkout(bad)).rejects.toThrow();expect(store.begin).not.toHaveBeenCalled();expect(client.createOrder).not.toHaveBeenCalled();});
 it.each([new SquareApiError("transient","generic",503),new Error("unknown private provider failure")])("resumes an unknown create outcome with the same deterministic provider key",async(error)=>{const {service,store,client}=setup();vi.mocked(client.createOrder).mockRejectedValueOnce(error).mockResolvedValueOnce(resources().order);await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"started"});await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"paid"});expect(client.createOrder).toHaveBeenCalledTimes(2);expect(vi.mocked(client.createOrder).mock.calls[0][0]).toEqual(vi.mocked(client.createOrder).mock.calls[1][0]);});
 it("marks only a definitive payment rejection failed, allowing a fresh browser token/key",async()=>{const {service,store,client}=setup();vi.mocked(client.createPayment).mockRejectedValueOnce(new SquareApiError("permanent","generic",402));await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"failed"});expect(store.value.squarePaymentId).toBeUndefined();});
 it("does not classify order rejection or malformed payment success as a card decline",async()=>{const first=setup();vi.mocked(first.client.createOrder).mockRejectedValueOnce(new SquareApiError("permanent","generic",400));await expect(first.service.checkout(input)).resolves.toMatchObject({state:"started"});const second=setup();vi.mocked(second.client.createPayment).mockResolvedValueOnce({private:"buyer@example.edu"});await expect(second.service.checkout(input)).resolves.toMatchObject({state:"order_created"});});
 it("retries readback without creating again when a persisted payment read is unavailable",async()=>{const {service,store,client}=setup();vi.mocked(client.getPayment).mockRejectedValueOnce(new SquareApiError("permanent","generic",404));await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"payment_created"});await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"paid"});expect(client.createOrder).toHaveBeenCalledOnce();expect(client.createPayment).toHaveBeenCalledOnce();expect(client.getPayment).toHaveBeenCalledTimes(2);});
 it("safely repeats createPayment when recording its returned ID fails",async()=>{const {service,store,client}=setup();store.recordPayment.mockRejectedValueOnce(new Error("store unavailable"));await expect(service.checkout(input)).resolves.toMatchObject({state:"order_created"});await expect(service.checkout(input)).resolves.toMatchObject({state:"paid"});expect(client.createPayment).toHaveBeenCalledTimes(2);expect(vi.mocked(client.createPayment).mock.calls[0][0]).toEqual(vi.mocked(client.createPayment).mock.calls[1][0]);});
 it.each([
  ["order state",(r:{order:SquareResource;payment:SquareResource})=>{r.order.state="CANCELED";}],
  ["tax",(r:{order:SquareResource;payment:SquareResource})=>{r.order.taxes=[{}];}],
  ["discount",(r:{order:SquareResource;payment:SquareResource})=>{r.order.discounts=[{}];}],
  ["service charge",(r:{order:SquareResource;payment:SquareResource})=>{r.order.service_charges=[{}];}],
  ["reward",(r:{order:SquareResource;payment:SquareResource})=>{r.order.rewards=[{}];}],
  ["modifier",(r:{order:SquareResource;payment:SquareResource})=>{(r.order.line_items as SquareResource[])[0].modifiers=[{}];}],
  ["tip",(r:{order:SquareResource;payment:SquareResource})=>{r.payment.tip_money={amount:1,currency:"USD"};}],
  ["rounding",(r:{order:SquareResource;payment:SquareResource})=>{r.order.rounding_adjustment={amount_money:{amount:0,currency:"USD"}};}],
  ["quantity",(r:{order:SquareResource;payment:SquareResource})=>{(r.order.line_items as SquareResource[])[0].quantity="2";}],
  ["alias",(r:{order:SquareResource;payment:SquareResource})=>{r.payment.id="ORDER_1";r.payment.order_id="ORDER_1";}],
  ["payment order drift",(r:{order:SquareResource;payment:SquareResource})=>{r.payment.order_id="OTHER";}],
  ["payment location",(r:{order:SquareResource;payment:SquareResource})=>{r.payment.location_id="OTHER";}],
  ["order location",(r:{order:SquareResource;payment:SquareResource})=>{r.order.location_id="OTHER";}],
  ["currency",(r:{order:SquareResource;payment:SquareResource})=>{r.order.total_money={amount:6000,currency:"CAD"};}],
 ])("never reports paid for strict invariant drift: %s",async(_label,mutate)=>{const {service,store}=setup(mutate);await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state:"operator_review"});});
 it.each(["paid","activated","failed"] as const)("returns terminal %s without contacting Square",async(state)=>{const {service,store,client}=setup();store.value={...store.value,state};await expect(service.checkout(input)).resolves.toEqual({attemptId:store.value.id,state});expect(client.createOrder).not.toHaveBeenCalled();expect(client.createPayment).not.toHaveBeenCalled();});
});
