import { describe,expect,it,vi } from "vitest";
import { createKitchenOrderBody,processKitchenClaim,runKitchenOrderBatch,verifyCancelledKitchenOrder,verifyCreatedKitchenOrder } from "../kitchen-order-worker";
import type { KitchenClaim } from "../postgres-kitchen-job-store";
const claim:KitchenClaim={leaseToken:"lease",action:"create",redemptionId:"11111111-1111-4111-8111-111111111111",locationId:"LPPWSSV03BHK8",referenceId:"11111111-1111-4111-8111-111111111111",idempotencyKey:"du-create-11111111-1111-4111-8111-111111111111",mealName:"Meal",mealCatalogObjectId:"MEAL_VARIATION",modifiers:[{squareCatalogObjectId:"MOD_B"},{squareCatalogObjectId:"MOD_A"}],squareOrderId:null,squareOrderVersion:null};
const zero={amount:0,currency:"USD"};
const response={id:"ORDER_1",version:7,location_id:"LPPWSSV03BHK8",reference_id:claim.referenceId,state:"OPEN",total_money:zero,total_tax_money:zero,total_discount_money:zero,total_tip_money:zero,total_service_charge_money:zero,line_items:[{quantity:"1",catalog_object_id:"MEAL_VARIATION",base_price_money:zero,total_money:zero,modifiers:[{catalog_object_id:"MOD_A",base_price_money:zero,total_price_money:zero},{catalog_object_id:"MOD_B",base_price_money:zero,total_price_money:zero}]}],fulfillments:[{type:"PICKUP",state:"PROPOSED",pickup_details:{schedule_type:"ASAP",recipient:{display_name:"Downtown U"}}}]};
describe("Square kitchen order worker",()=>{
 it("builds fixed location, PII-free pickup with stable provider key and exact catalog snapshot",()=>{const body=createKitchenOrderBody(claim);expect(body).toEqual({idempotency_key:claim.idempotencyKey,order:{location_id:"LPPWSSV03BHK8",reference_id:claim.referenceId,line_items:[{quantity:"1",catalog_object_id:"MEAL_VARIATION",base_price_money:zero,modifiers:[{catalog_object_id:"MOD_A",base_price_money:zero},{catalog_object_id:"MOD_B",base_price_money:zero}]}],fulfillments:[{type:"PICKUP",state:"PROPOSED",pickup_details:{schedule_type:"ASAP",recipient:{display_name:"Downtown U"}}}]}});expect(JSON.stringify(body)).not.toMatch(/email|phone/i)});
 // Deliberately mutate provider-shaped fixtures to exercise hostile response drift.
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
 it("rejects location, reference, state, quantity, item, modifier and fulfillment mismatches",()=>{for(const mutation of [(x:any)=>x.location_id="OTHER",(x:any)=>x.reference_id="other",(x:any)=>x.state="COMPLETED",(x:any)=>x.line_items[0].quantity="2",(x:any)=>x.line_items[0].catalog_object_id="OTHER",(x:any)=>x.line_items[0].modifiers=[], (x:any)=>x.line_items[0].base_price_money.amount=1,(x:any)=>x.total_money.amount=1,(x:any)=>x.taxes=[{}],(x:any)=>x.discounts=[{}],(x:any)=>x.service_charges=[{}],(x:any)=>x.fulfillments=[], (x:any)=>x.fulfillments[0].pickup_details.recipient.display_name="Student",(x:any)=>x.fulfillments[0].pickup_details.recipient.email_address="student@example.edu"]){const x=structuredClone(response);mutation(x);expect(()=>verifyCreatedKitchenOrder(x,claim)).toThrow(/mismatch/)}});
 it("persists only after exact provider verification and retries ambiguous results with the same DB claim",async()=>{const store={finalize:vi.fn().mockResolvedValue("created"),fail:vi.fn().mockResolvedValue("pending")};const square={locationId:"LPPWSSV03BHK8",createOrder:vi.fn().mockResolvedValue(response)};await processKitchenClaim(store as never,square as never,claim);expect(store.finalize).toHaveBeenCalledWith(claim,"ORDER_1",7);expect(store.fail).not.toHaveBeenCalled();square.createOrder.mockRejectedValueOnce(new Error("timeout"));await processKitchenClaim(store as never,square as never,claim);expect(store.fail).toHaveBeenLastCalledWith(claim,"provider_ambiguous",false,30,null)});
 it("quarantines verified-response mismatch instead of silently accepting an orphan",async()=>{const store={finalize:vi.fn(),fail:vi.fn().mockResolvedValue("operator_review")};const square={locationId:"LPPWSSV03BHK8",createOrder:vi.fn().mockResolvedValue({...response,location_id:"OTHER"})};await processKitchenClaim(store as never,square as never,claim);expect(store.finalize).not.toHaveBeenCalled();expect(store.fail).toHaveBeenCalledWith(claim,"provider_mismatch",true,60,{id:"ORDER_1",version:7})});
 it("verifies cancelled ticket identity, catalog, zero-dollar economics and generic recipient",()=>{const cancelClaim={...claim,action:"cancel" as const,idempotencyKey:"du-cancel-11111111-1111-4111-8111-111111111111",squareOrderId:"ORDER_1",squareOrderVersion:7},cancelled={...structuredClone(response),state:"CANCELED",version:8};cancelled.fulfillments[0].state="CANCELED";expect(verifyCancelledKitchenOrder(cancelled,cancelClaim)).toEqual({id:"ORDER_1",version:8});for(const changed of [{...structuredClone(cancelled),total_money:{amount:1,currency:"USD"}},{...structuredClone(cancelled),line_items:[]},{...structuredClone(cancelled),fulfillments:[]}])expect(()=>verifyCancelledKitchenOrder(changed,cancelClaim)).toThrow(/mismatch/)});
 it("surfaces a provider result whose success or failure cannot be durably persisted",async()=>{const store={finalize:vi.fn().mockResolvedValue(false),fail:vi.fn().mockResolvedValue(false)},square={locationId:"LPPWSSV03BHK8",createOrder:vi.fn().mockResolvedValue(response)};await expect(processKitchenClaim(store as never,square as never,claim)).rejects.toThrow("could not be persisted")});
 it("finalizes exact cancellation, retries ambiguity with the same key, and surfaces cancellation persistence loss",async()=>{const cancelClaim={...claim,action:"cancel" as const,idempotencyKey:"du-cancel-11111111-1111-4111-8111-111111111111",squareOrderId:"ORDER_1",squareOrderVersion:7},cancelled={...structuredClone(response),state:"CANCELED",version:8};cancelled.fulfillments[0].state="CANCELED";const store={finalize:vi.fn().mockResolvedValue("cancelled"),fail:vi.fn().mockResolvedValue("cancel_pending")},square={locationId:"LPPWSSV03BHK8",updateOrder:vi.fn().mockResolvedValue(cancelled)};expect(await processKitchenClaim(store as never,square as never,cancelClaim)).toBe("completed");expect(square.updateOrder).toHaveBeenCalledWith("ORDER_1",expect.objectContaining({idempotency_key:cancelClaim.idempotencyKey}));expect(store.finalize).toHaveBeenCalledWith(cancelClaim,"ORDER_1",8);square.updateOrder.mockRejectedValueOnce(new Error("timeout"));expect(await processKitchenClaim(store as never,square as never,cancelClaim)).toBe("deferred");expect(store.fail).toHaveBeenLastCalledWith(cancelClaim,"provider_ambiguous",false,30,null);store.finalize.mockResolvedValueOnce(false);store.fail.mockResolvedValueOnce(false);square.updateOrder.mockResolvedValueOnce(cancelled);await expect(processKitchenClaim(store as never,square as never,cancelClaim)).rejects.toThrow("could not be persisted")});
 it("checks the time budget before each one-row claim so untouched jobs never consume attempts",async()=>{const claimJob=vi.fn(),clock=vi.spyOn(Date,"now").mockReturnValueOnce(0).mockReturnValue(1000);try{expect(await runKitchenOrderBatch({claim:claimJob} as never,{} as never,20,1000)).toEqual({claimed:0,completed:0,deferred:0});expect(claimJob).not.toHaveBeenCalled()}finally{clock.mockRestore()}});
 it("claims just in time rather than leasing a batch ahead of provider processing",async()=>{const store={claim:vi.fn().mockResolvedValueOnce([claim]).mockResolvedValueOnce([]),finalize:vi.fn().mockResolvedValue("created"),fail:vi.fn()},square={locationId:"LPPWSSV03BHK8",createOrder:vi.fn().mockResolvedValue(response)};expect(await runKitchenOrderBatch(store as never,square as never,2,1000)).toEqual({claimed:1,completed:1,deferred:0});expect(store.claim).toHaveBeenNthCalledWith(1,1);expect(store.claim).toHaveBeenNthCalledWith(2,1)});
});
