import { beforeEach, describe, expect, it, vi } from "vitest";
import { createAuthCryptography } from "../auth";
import { PostgresStudentPortalStore } from "../postgres-student-portal-store";
import { createStudentPortalHandler, parseSessionCookie, PortalConflictError, PortalInsufficientCreditsError, PortalInvalidRequestError, PortalNotFoundError, PortalRateLimitError, STUDENT_PORTAL_SECURITY_HEADERS, type PortalEndpoint, type StudentPortalStore } from "../student-portal";

const origin="https://app.example.test"; const sid="A".repeat(43); const bearer="B".repeat(43);
const secret=Buffer.from(Array.from({length:32},(_,i)=>i+1)).toString("base64url");
const credential=`v1.${sid}.${bearer}`; const studentId="11111111-1111-4111-8111-111111111111";
const auth={validateSession:vi.fn(),revokeSession:vi.fn()};
const store:StudentPortalStore={me:vi.fn(),meals:vi.fn(),purchases:vi.fn(),reservations:vi.fn(),reserve:vi.fn(),reverse:vi.fn()};
function handler(endpoint:PortalEndpoint){return createStudentPortalHandler({endpoint,allowedOrigin:origin,authStore:auth as never,cryptography:createAuthCryptography(secret),store})}
function headers(post=false,extra:Record<string,string|string[]|undefined>={}){return{cookie:`downtown_u_session=${credential}`,...(post?{origin,"content-type":"application/json"}:{}),...extra}}
function call(endpoint:PortalEndpoint,method:string,body?:unknown,extra:Record<string,string|string[]|undefined>={},query?:Record<string,string|string[]|undefined>){return handler(endpoint)({method,headers:headers(method==="POST",extra),body,query,reservationId:endpoint==="reservation-cancel"?"22222222-2222-4222-8222-222222222222":undefined})}

beforeEach(()=>{vi.clearAllMocks();auth.validateSession.mockResolvedValue({outcome:"valid",studentId});auth.revokeSession.mockResolvedValue({outcome:"accepted"});vi.mocked(store.me).mockResolvedValue({studentId,availableCredits:2});vi.mocked(store.meals).mockResolvedValue([{id:"meal",name:"Meal",baseCredits:1,modifiers:[]}]);vi.mocked(store.purchases).mockResolvedValue({items:[],nextCursor:null});vi.mocked(store.reservations).mockResolvedValue({items:[],nextCursor:null});vi.mocked(store.reserve).mockResolvedValue({id:"22222222-2222-4222-8222-222222222222",mealId:"meal",mealName:"Meal",modifiers:[],credits:1,status:"reserved",reservedAt:"2026-08-05T00:00:00Z",expiresAt:"2026-08-05T00:15:00Z"});vi.mocked(store.reverse).mockResolvedValue({id:"22222222-2222-4222-8222-222222222222",mealId:"meal",mealName:"Meal",modifiers:[],credits:1,status:"reversed",reservedAt:"2026-08-05T00:00:00Z",expiresAt:"2026-08-05T00:15:00Z"})});

describe("student portal HTTP core",()=>{
 it("accepts one v1 cookie and rejects absent, malformed, duplicate, oversized and control-bearing cookies",()=>{expect(parseSessionCookie(`x=1; downtown_u_session=${credential}`)).toEqual({sessionId:sid,bearer});for(const raw of [undefined,"",`downtown_u_session=v2.${sid}.${bearer}`,`downtown_u_session=${credential}; downtown_u_session=${credential}`,`downtown_u_session=${credential}\r`,"x="+"a".repeat(4097)])expect(parseSessionCookie(raw)).toBeNull()});
 it("does not invoke inherited or accessor cookie headers and maps header arrays to generic 401",async()=>{const getter=vi.fn(()=>credential);const accessor={};Object.defineProperty(accessor,"cookie",{enumerable:true,get:getter});for(const h of [Object.create({cookie:`downtown_u_session=${credential}`}),accessor,{cookie:[`downtown_u_session=${credential}`]}]){const result=await handler("me")({method:"GET",headers:h as never});expect(result).toMatchObject({status:401,body:{error:"unauthorized"}})}expect(getter).not.toHaveBeenCalled()});
 it("makes absent, invalid, throwing, and malformed validation outcomes the exact same 401",async()=>{const cases:[Record<string,string|string[]|undefined>,unknown][]=[[{},null],[headers(),{outcome:"invalid"}],[headers(),new Error("pii db")],[headers(),{outcome:"valid",studentId:"bad"}]];for(const [h,outcome] of cases){if(outcome instanceof Error)auth.validateSession.mockRejectedValueOnce(outcome);else if(outcome)auth.validateSession.mockResolvedValueOnce(outcome);const result=await handler("me")({method:"GET",headers:h});expect({status:result.status,body:result.body}).toEqual({status:401,body:{error:"unauthorized"}})} });
 it("passes the complete credential-bound principal and never reflects the credential",async()=>{const result=await call("me","GET");expect(store.me).toHaveBeenCalledWith({studentId,sessionId:sid,digest:expect.any(Buffer)});expect(JSON.stringify(result)).not.toContain(bearer);expect(result.headers).toMatchObject(STUDENT_PORTAL_SECURITY_HEADERS)});
 it.each([["me","POST","GET"],["meals","post","GET"],["purchases","HEAD","GET"],["reservation-cancel","GET","POST"],["logout","GET","POST"]] as const)("enforces exact methods for %s",async(endpoint,method,allow)=>{const result=await call(endpoint,method);expect(result.status).toBe(405);expect(result.headers.Allow).toBe(allow)});
 it("rejects GET bodies and entity headers before authentication or store access",async()=>{for(const request of [{body:{}},{extra:{"content-length":"0"}},{extra:{"transfer-encoding":"chunked"}},{extra:{"content-type":"application/json"}}]){const result=await handler("me")({method:"GET",headers:headers(false,request.extra),body:request.body});expect(result.status).toBe(400)}expect(auth.validateSession).not.toHaveBeenCalled();expect(store.me).not.toHaveBeenCalled()});
 it("rejects cross-origin reads while allowing same-origin and originless reads",async()=>{expect((await call("me","GET",undefined,{origin:"https://evil.test"})).status).toBe(403);expect((await call("me","GET",undefined,{origin})).status).toBe(200);expect((await call("me","GET")).status).toBe(200)});
 it("validates list query descriptors, arrays, unknowns, cursor characters, and limit bounds",async()=>{const accessor={};const getter=vi.fn(()=>"1");Object.defineProperty(accessor,"limit",{enumerable:true,get:getter});for(const query of [{limit:["1"]},{unknown:"1"},{limit:"0"},{limit:"101"},{limit:"01"},{cursor:"bad!"},Object.create({limit:"1"}),accessor])expect((await call("purchases","GET",undefined,{},query as never)).status).toBe(400);expect(getter).not.toHaveBeenCalled();expect((await call("purchases","GET",undefined,{}, {limit:"100",cursor:"abc.def"})).status).toBe(200);expect(store.purchases).toHaveBeenLastCalledWith(expect.anything(),{limit:100,cursor:"abc.def"})});
 it("requires exact same-origin JSON mutations and rejects cross-site fetch metadata",async()=>{const body={mealId:"meal",modifierIds:[],idempotencyKey:"C".repeat(43)};expect((await call("reservations","POST",body,{origin:"https://evil.test"})).status).toBe(403);expect((await call("reservations","POST",body,{"sec-fetch-site":"cross-site"})).status).toBe(403);expect((await call("reservations","POST",body,{"content-type":"text/plain"})).status).toBe(415);expect((await call("reservations","POST",body,{"sec-fetch-site":"same-origin"})).status).toBe(201)});
 it("accepts only an exact reservation object and no client-controlled credits, names, or catalog fields",async()=>{const valid={mealId:"meal",modifierIds:[],idempotencyKey:"C".repeat(43)};expect((await call("reservations","POST",valid)).status).toBe(201);for(const extra of ["credits","name","catalogId"]){expect((await call("reservations","POST",{...valid,[extra]:1})).status).toBe(400)}expect(store.reserve).toHaveBeenCalledTimes(1)});
 it("fails closed rather than emitting oversized meal or modifier collections",async()=>{vi.mocked(store.meals).mockResolvedValueOnce(Array.from({length:101},(_,i)=>({id:`meal-${i}`,name:"Meal",baseCredits:1,modifiers:[]})));expect((await call("meals","GET")).status).toBe(503);vi.mocked(store.meals).mockResolvedValueOnce([{id:"meal",name:"Meal",baseCredits:1,modifiers:Array.from({length:51},(_,i)=>({id:`modifier-${i}`,name:"Modifier",creditDelta:0}))}]);expect((await call("meals","GET")).status).toBe(503)});
 it("rejects malformed modifier arrays without invoking accessors",async()=>{const base={mealId:"meal",idempotencyKey:"C".repeat(43)};const hole=new Array(1);const accessor:string[]=[];Object.defineProperty(accessor,"0",{enumerable:true,get:()=>{throw new Error("must not run")}});accessor.length=1;const symbol:string[]=[];(symbol as unknown as Record<symbol,string>)[Symbol("x")]="x";for(const modifierIds of [hole,accessor,symbol,["x","x"],Array(11).fill("x"),["bad!"],Object.setPrototypeOf(["x"],null)])expect((await call("reservations","POST",{...base,modifierIds})).status).toBe(400)});
 it("maps public errors exactly without leaking PII or causes",async()=>{const cases=[[new PortalInvalidRequestError(),400,"invalid_request"],[new PortalNotFoundError(),404,"not_found"],[new PortalInsufficientCreditsError(),409,"insufficient_credits"],[new PortalConflictError(),409,"conflict"],[new PortalRateLimitError(),429,"rate_limited"],[new Error("student@example.test database cause"),503,"unavailable"]] as const;for(const [error,status,code] of cases){vi.mocked(store.me).mockRejectedValueOnce(error);const result=await call("me","GET");expect({status:result.status,body:result.body}).toEqual({status,body:{error:code}});expect(JSON.stringify(result)).not.toMatch(/student@example|database cause/);if(status===429)expect(result.headers["Retry-After"]).toBe("600")}});
 it("logout returns bodyless 204 and clears the cookie",async()=>{const result=await call("logout","POST",{});expect(result.status).toBe(204);expect(result).not.toHaveProperty("body");expect(result.headers["Set-Cookie"]).toContain("Max-Age=0");expect(auth.revokeSession).toHaveBeenCalledWith({sessionId:sid,digest:expect.any(Buffer)})});
 it("logout still clears the cookie but returns generic 503 when revocation throws",async()=>{auth.revokeSession.mockRejectedValueOnce(new Error("student@example.test database cause"));const result=await call("logout","POST",{});expect({status:result.status,body:result.body}).toEqual({status:503,body:{error:"unavailable"}});expect(result.headers["Set-Cookie"]).toContain("Max-Age=0");expect(JSON.stringify(result.body)).not.toMatch(/student@example|database cause/)});
});

describe("portal cursors",()=>{it("rejects tampered, endpoint-swapped, and student-swapped cursors",async()=>{const payload=(id:string)=>({id,planId:"plan",creditsGranted:2,priceCents:100,currency:"USD",status:"paid",refundedCredits:0,paidAt:"2026-08-05T00:00:00Z",createdAt:"2026-08-05T00:00:00Z"});const client={query:vi.fn(async(sql:string)=>sql==="BEGIN"||sql==="COMMIT"?{rows:[],rowCount:null}:{rows:[{payload:payload("22222222-2222-4222-8222-222222222222")},{payload:payload("33333333-3333-4333-8333-333333333333")}],rowCount:2}),release:vi.fn()};const pool={connect:vi.fn().mockResolvedValue(client)} as never;const pg=new PostgresStudentPortalStore(pool,async()=>{});const principal={studentId,sessionId:sid,digest:Buffer.alloc(32,7)};const page=await pg.purchases(principal,{limit:1,cursor:null});expect(page.nextCursor).toEqual(expect.any(String));const cursor=page.nextCursor!;await expect(pg.purchases(principal,{limit:1,cursor:cursor.slice(0,-1)+"A"})).rejects.toBeInstanceOf(PortalInvalidRequestError);await expect(pg.reservations(principal,{limit:1,cursor})).rejects.toBeInstanceOf(PortalInvalidRequestError);await expect(pg.purchases({...principal,studentId:"44444444-4444-4444-8444-444444444444"},{limit:1,cursor})).rejects.toBeInstanceOf(PortalInvalidRequestError)})});
