import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { Pool } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { assertDowntownURuntimeIdentity } from "../postgres-runtime-identity";
import { assertDowntownUJobRuntimeIdentity } from "../postgres-job-runtime-identity";

const baseUrl=process.env.TEST_DATABASE_URL;const run=baseUrl?describe:describe.skip;
const suffix=`${process.pid}_${Date.now()}`;const databaseName=`downtown_u_portal_${suffix}`;const login=`downtown_u_portal_app_${suffix}`;const jobLogin=`downtown_u_portal_job_${suffix}`;
let admin:Pool;let owner:Pool;let runtime:Pool;let jobs:Pool;
const migrations=[1,2,3,4,5,6,7].map(n=>readFileSync(resolve(process.cwd(),`db/migrations/20260804000${n}_${["downtown_u_phase1","downtown_u_webhook_events","downtown_u_payment_activation","downtown_u_refund_activation","downtown_u_auth","downtown_u_student_portal","downtown_u_checkout"][n-1]}.sql`),"utf8"));
const q=(x:string)=>`"${x.replaceAll('"','""')}"`;
interface Principal{student:string;session:string;digest:Buffer}
async function principal(tag:string,credits=5):Promise<Principal>{const student=(await owner.query<{id:string}>("INSERT INTO downtown_u_students(normalized_email,eligibility_status,eligibility_reviewed_at,approved_at) VALUES($1,'approved',clock_timestamp(),clock_timestamp()) RETURNING id",[`${tag}@example.edu`])).rows[0].id;if(credits>0){const purchase=(await owner.query<{id:string}>(`INSERT INTO downtown_u_plan_purchases(student_id,plan_id,credits_granted,price_cents,square_payment_id,square_order_id,source_event_id,paid_at) VALUES($1,'flex-5',5,6000,$2,$3,$4,clock_timestamp()) RETURNING id`,[student,`${tag}-pay`,`${tag}-order`,`${tag}-event`])).rows[0].id;await owner.query(`INSERT INTO downtown_u_credit_transactions(student_id,purchase_id,delta,resulting_balance,transaction_type,reason,idempotency_key,actor_type,actor_id,source_type,source_id) VALUES($1,$2,5,5,'purchase_grant','verified',$3,'system','test','test',$4)`,[student,purchase,`${tag}-grant`,`${tag}-grant-source`]);if(credits<5){const redemption=(await owner.query<{id:string}>("INSERT INTO downtown_u_redemptions(student_id,credits,idempotency_key) VALUES($1,$2,$3) RETURNING id",[student,5-credits,`${tag}-warm`])).rows[0].id;await owner.query(`INSERT INTO downtown_u_credit_transactions(student_id,redemption_id,delta,resulting_balance,transaction_type,reason,idempotency_key,actor_type,actor_id,source_type,source_id) VALUES($1,$2,$3,$4,'reservation','warm',$5,'system','test','test',$6)`,[student,redemption,-(5-credits),credits,`${tag}-warm-ledger`,`${tag}-warm-source`]);}}
 const session=createHash("sha256").update(`session:${tag}`).digest("base64url");const token=createHash("sha256").update(`token:${tag}`).digest();await owner.query("INSERT INTO downtown_u_auth_sessions(session_id,student_id,verifier_version,token_digest,expires_at) VALUES($1,$2,1,$3,clock_timestamp()+interval '1 hour')",[session,student,token]);return{student,session,digest:token}}
const args=(p:Principal)=>[p.session,1,p.digest];
async function reserve(p:Principal,key:string,meal="meal",modifiers:string[]=[]){return(await runtime.query<{payload:Record<string,unknown>}>("SELECT payload FROM public.downtown_u_student_reserve($1,$2::smallint,$3::bytea,$4,$5::text[],$6)",[...args(p),meal,modifiers,key])).rows[0].payload}
async function reverse(p:Principal,id:string,key:string){return(await runtime.query<{payload:Record<string,unknown>}>("SELECT payload FROM public.downtown_u_student_reverse($1,$2::smallint,$3::bytea,$4::uuid,$5)",[...args(p),id,key])).rows[0].payload}
async function grantFive(p:Principal,tag:string){const balance=Number((await owner.query("SELECT credit_balance FROM downtown_u_students WHERE id=$1",[p.student])).rows[0].credit_balance);const purchase=(await owner.query<{id:string}>("INSERT INTO downtown_u_plan_purchases(student_id,plan_id,credits_granted,price_cents,square_payment_id,square_order_id,source_event_id,paid_at) VALUES($1,'flex-5',5,6000,$2,$3,$4,clock_timestamp()) RETURNING id",[p.student,`${tag}-pay`,`${tag}-order`,`${tag}-event`])).rows[0].id;await owner.query("INSERT INTO downtown_u_credit_transactions(student_id,purchase_id,delta,resulting_balance,transaction_type,reason,idempotency_key,actor_type,actor_id,source_type,source_id) VALUES($1,$2,5,$3,'purchase_grant','verified',$4,'system','test','test',$5)",[p.student,purchase,balance+5,`${tag}-grant`,`${tag}-source`])}

run.sequential("Phase 4 protected portal capabilities on PostgreSQL 16",()=>{
 beforeAll(async()=>{const parsed=new URL(baseUrl!);const local=["localhost","127.0.0.1","::1"].includes(parsed.hostname);if(!local&&!/(test|disposable)/i.test(parsed.pathname))throw new Error("unsafe TEST_DATABASE_URL");admin=new Pool({connectionString:baseUrl,max:2});await admin.query(`CREATE DATABASE ${q(databaseName)}`);await admin.query(`GRANT CREATE ON DATABASE ${q(databaseName)} TO PUBLIC`);parsed.pathname=`/${databaseName}`;owner=new Pool({connectionString:parsed.toString(),max:8});expect((await owner.query("SELECT has_database_privilege('public',current_database(),'CREATE') allowed")).rows[0].allowed).toBe(true);for(const migration of migrations)await owner.query(migration);expect((await owner.query("SELECT has_database_privilege('public',current_database(),'CREATE') allowed")).rows[0].allowed).toBe(false);await owner.query("INSERT INTO downtown_u_meal_rules(id,display_name,square_catalog_object_id,base_credits,active) VALUES('meal','Public Meal','sq-private-meal',2,true),('other','Other Meal','sq-private-other',1,true),('inactive','Inactive','sq-private-inactive',1,false),('future','Future','sq-private-future',1,true)");await owner.query("UPDATE downtown_u_meal_rules SET available_from=clock_timestamp()+interval '1 day' WHERE id='future'");await owner.query("INSERT INTO downtown_u_meal_modifiers(id,meal_id,display_name,square_catalog_object_id,credit_delta,active) VALUES('extra','meal','Extra','sq-private-extra',1,true),('off','meal','Off','sq-private-off',1,false),('othermod','other','Other mod','sq-private-othermod',1,true)");await admin.query(`CREATE ROLE ${q(login)} LOGIN`);await admin.query(`CREATE ROLE ${q(jobLogin)} LOGIN`);await admin.query(`GRANT downtown_u_runtime TO ${q(login)}`);await admin.query(`GRANT downtown_u_jobs TO ${q(jobLogin)}`);parsed.username=login;parsed.password="";runtime=new Pool({connectionString:parsed.toString(),max:8});parsed.username=jobLogin;jobs=new Pool({connectionString:parsed.toString(),max:8});await assertDowntownURuntimeIdentity(runtime as never);await assertDowntownUJobRuntimeIdentity(jobs as never)},30_000);
 afterAll(async()=>{await runtime?.end();await jobs?.end();await owner?.end();if(admin){await admin.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1",[databaseName]);await admin.query(`DROP DATABASE IF EXISTS ${q(databaseName)}`);await admin.query(`DROP ROLE IF EXISTS ${q(login)}`);await admin.query(`DROP ROLE IF EXISTS ${q(jobLogin)}`);await admin.end()}},30_000);
 it("scopes me and lists to the exact live credential",async()=>{const a=await principal("portal-a");const b=await principal("portal-b");const me=(await runtime.query("SELECT payload FROM public.downtown_u_student_me($1,$2::smallint,$3::bytea)",args(a))).rows[0].payload;expect(me).toMatchObject({studentId:a.student,availableCredits:5,eligibilityStatus:"approved"});expect(JSON.stringify(me)).not.toContain("square");await expect(runtime.query("SELECT payload FROM public.downtown_u_student_me($1,$2::smallint,$3::bytea)",[a.session,1,b.digest])).rejects.toThrow(/invalid principal/);expect((await runtime.query("SELECT payload FROM public.downtown_u_student_purchases($1,$2::smallint,$3::bytea,101,NULL,NULL)",args(a))).rowCount).toBe(1)});
 it("debits once and returns the exact reservation on retry",async()=>{const p=await principal("reserve-once");const key="reserve_once_key_1234";const first=await reserve(p,key);const retry=await reserve(p,key);expect(retry).toEqual(first);expect(first).toMatchObject({status:"reserved",credits:2,mealId:"meal"});expect((await owner.query("SELECT credit_balance FROM downtown_u_students WHERE id=$1",[p.student])).rows[0].credit_balance).toBe(3);expect((await owner.query("SELECT count(*)::int count FROM downtown_u_credit_transactions WHERE redemption_id=$1",[first.id])).rows[0].count).toBe(1);await expect(reserve(p,key,"other")).rejects.toThrow(/idempotency conflict/)});
 it("rejects insufficient credits and serializes concurrent last-credit reserves",async()=>{const p=await principal("concurrent",1);await expect(reserve(p,"too_many_credits_123")).rejects.toThrow(/insufficient credits/);const settled=await Promise.allSettled([reserve(p,"concurrent_key_one","other"),reserve(p,"concurrent_key_two","other")]);expect(settled.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(settled.filter(x=>x.status==="rejected")).toHaveLength(1);expect((await owner.query("SELECT credit_balance FROM downtown_u_students WHERE id=$1",[p.student])).rows[0].credit_balance).toBe(0)});
 it("reverses once; retry is stable and another key conflicts",async()=>{const p=await principal("reverse-once");const r=await reserve(p,"reserve_for_reverse1");const first=await reverse(p,String(r.id),"reverse_same_key_12");expect(first.status).toBe("reversed");expect(await reverse(p,String(r.id),"reverse_same_key_12")).toEqual(first);await expect(reverse(p,String(r.id),"reverse_other_key_1")).rejects.toThrow(/not cancellable/);expect((await owner.query("SELECT credit_balance FROM downtown_u_students WHERE id=$1",[p.student])).rows[0].credit_balance).toBe(5);expect((await owner.query("SELECT count(*)::int count FROM downtown_u_credit_transactions WHERE redemption_id=$1",[r.id])).rows[0].count).toBe(2)});
 it("does not reveal another student's reservation and rejects dead sessions",async()=>{const a=await principal("owner-r");const b=await principal("other-r");const r=await reserve(a,"owner_reservation_1");await expect(reverse(b,String(r.id),"wrong_owner_key_12")).rejects.toThrow(/not found/);await owner.query("UPDATE downtown_u_auth_sessions SET revoked_at=clock_timestamp() WHERE session_id=$1",[a.session]);await expect(reserve(a,"revoked_session_key")).rejects.toThrow(/invalid principal/);await owner.query("UPDATE downtown_u_students SET eligibility_status='suspended',suspended_at=clock_timestamp() WHERE id=$1",[b.student]);await expect(runtime.query("SELECT payload FROM public.downtown_u_student_me($1,$2::smallint,$3::bytea)",args(b))).rejects.toThrow(/invalid principal/)});
 it("rejects nullable/malformed direct calls and all direct table/helper access",async()=>{const p=await principal("malformed");await expect(runtime.query("SELECT * FROM public.downtown_u_student_purchases($1,$2::smallint,$3::bytea,NULL,NULL,NULL)",args(p))).rejects.toThrow(/invalid request/);await expect(runtime.query("SELECT public.downtown_u_student_principal($1,$2::smallint,$3::bytea)",args(p))).rejects.toMatchObject({code:"42501"});await expect(runtime.query("SELECT * FROM public.downtown_u_students")).rejects.toMatchObject({code:"42501"});await expect(runtime.query("SELECT payload FROM public.downtown_u_student_me(NULL,NULL,NULL)")).rejects.toThrow(/invalid principal/)});
 it("publishes only active in-window meals and strips every Square identifier",async()=>{const p=await principal("menu");const rows=(await runtime.query("SELECT payload FROM downtown_u_student_meals($1,$2::smallint,$3::bytea)",args(p))).rows;expect(rows.map(x=>x.payload.id)).toEqual(["meal","other"]);expect(JSON.stringify(rows)).not.toContain("sq-private");expect(rows[0].payload.modifiers).toEqual([{id:"extra",name:"Extra",creditDelta:1}])});
 it("uses trusted active modifiers and rejects inactive or cross-meal tampering",async()=>{const p=await principal("modifier");expect(await reserve(p,"modifier_valid_key","meal",["extra"])).toMatchObject({credits:3,modifiers:[{id:"extra",name:"Extra",creditDelta:1}]});await expect(reserve(p,"modifier_off_key_1","meal",["off"])).rejects.toThrow(/invalid request/);await expect(reserve(p,"modifier_cross_key","meal",["othermod"])).rejects.toThrow(/invalid request/)});
 it("rejects duplicate, null, shifted and multidimensional modifier arrays",async()=>{const p=await principal("arrays");const sql="SELECT * FROM downtown_u_student_reserve($1,$2::smallint,$3::bytea,'meal',$4::text[],$5)";await expect(runtime.query(sql,[...args(p),["extra","extra"],"array_duplicate_key"])).rejects.toThrow(/invalid request/);await expect(runtime.query("SELECT * FROM downtown_u_student_reserve($1,$2::smallint,$3::bytea,'meal',ARRAY[['extra']]::text[],$4)",[...args(p),"array_multidim_key"])).rejects.toThrow(/invalid request/);await expect(runtime.query("SELECT * FROM downtown_u_student_reserve($1,$2::smallint,$3::bytea,'meal','[0:0]={extra}'::text[],$4)",[...args(p),"array_shifted_key_1"])).rejects.toThrow(/invalid request/);await expect(runtime.query(sql,[...args(p),[null],"array_null_key_123"])).rejects.toThrow(/invalid request/)});
 it("keeps snapshots private and immutable even to the owner",async()=>{const p=await principal("snapshot");const r=await reserve(p,"snapshot_private_1");await expect(runtime.query("SELECT * FROM downtown_u_reservation_snapshots")).rejects.toMatchObject({code:"42501"});await expect(owner.query("UPDATE downtown_u_reservation_snapshots SET credits=1 WHERE redemption_id=$1",[r.id])).rejects.toThrow(/immutable/);await expect(owner.query("DELETE FROM downtown_u_reservation_snapshots WHERE redemption_id=$1",[r.id])).rejects.toThrow(/immutable/)});
 it("serializes concurrent cancellation to one exact credit",async()=>{const p=await principal("cancel-race");const r=await reserve(p,"cancel_race_reserve");const settled=await Promise.allSettled([reverse(p,String(r.id),"cancel_race_key_1"),reverse(p,String(r.id),"cancel_race_key_2")]);expect(settled.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect((await owner.query("SELECT credit_balance FROM downtown_u_students WHERE id=$1",[p.student])).rows[0].credit_balance).toBe(5)});
 it("expires portal reservations exactly once across concurrent jobs",async()=>{const p=await principal("expiry");const r=await reserve(p,"expiry_reserve_key");await owner.query("UPDATE downtown_u_redemptions SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[r.id]);const results=await Promise.all([jobs.query("SELECT downtown_u_reverse_expired_reservations(100) n"),jobs.query("SELECT downtown_u_reverse_expired_reservations(100) n")]);expect(results.map(x=>x.rows[0].n).sort()).toEqual([0,1]);expect((await owner.query("SELECT credit_balance FROM downtown_u_students WHERE id=$1",[p.student])).rows[0].credit_balance).toBe(5);expect((await owner.query("SELECT count(*)::int n FROM downtown_u_credit_transactions WHERE redemption_id=$1",[r.id])).rows[0].n).toBe(2)});
 it("excludes expired legacy redemptions without portal snapshots",async()=>{const p=await principal("legacy");const id=(await owner.query<{id:string}>("INSERT INTO downtown_u_redemptions(student_id,credits,idempotency_key,expires_at) VALUES($1,1,'legacy_expiry_key',clock_timestamp()-interval '1 second') RETURNING id",[p.student])).rows[0].id;expect((await jobs.query("SELECT downtown_u_reverse_expired_reservations(100) n")).rows[0].n).toBe(0);expect((await owner.query("SELECT status FROM downtown_u_redemptions WHERE id=$1",[id])).rows[0].status).toBe("reserved")});
 it("keeps the web and job executable surfaces mutually isolated",async()=>{await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined();await expect(runtime.query("SELECT downtown_u_reverse_expired_reservations(1)")).rejects.toMatchObject({code:"42501"});expect((await jobs.query("SELECT downtown_u_reverse_expired_reservations(1) n")).rows[0].n).toBe(0);await expect(jobs.query("SELECT * FROM downtown_u_students")).rejects.toMatchObject({code:"42501"});await expect(jobs.query("SELECT downtown_u_student_principal(NULL,NULL,NULL)")).rejects.toMatchObject({code:"42501"});await expect(jobs.query("SELECT downtown_u_valid_modifier_snapshot('[]'::jsonb)")).rejects.toMatchObject({code:"42501"});await expect(jobs.query("SELECT * FROM downtown_u_reservation_snapshots")).rejects.toMatchObject({code:"42501"})});
 it("enforces canonical immutable reservation snapshots",async()=>{const p=await principal("snapshot-canonical");const malformed:[unknown,string][]=[
   [[{id:"a",name:"A",squareCatalogObjectId:"sq-a",creditDelta:1,extra:true}],"extra"],
   [[{id:"a",name:"A",squareCatalogObjectId:"sq-a"}],"missing"],
   [[{id:"a",name:"A",squareCatalogObjectId:"sq-a",creditDelta:1.5}],"fractional"],
   [[{id:"a",name:"A",squareCatalogObjectId:"sq-a",creditDelta:1e100}],"huge"],
   [[{id:"b",name:"B",squareCatalogObjectId:"sq-b",creditDelta:1},{id:"a",name:"A",squareCatalogObjectId:"sq-a",creditDelta:1}],"order"],
   [[{id:"a",name:"A",squareCatalogObjectId:"sq-a",creditDelta:1},{id:"a",name:"A",squareCatalogObjectId:"sq-b",creditDelta:1}],"duplicate"]
  ];for(const [mods,tag] of malformed){const redemption=(await owner.query<{id:string}>("INSERT INTO downtown_u_redemptions(student_id,credits,idempotency_key) VALUES($1,1,$2) RETURNING id",[p.student,`malformed-${tag}`])).rows[0].id;await expect(owner.query("INSERT INTO downtown_u_reservation_snapshots(redemption_id,meal_rule_id,meal_public_id,meal_display_name,meal_square_catalog_object_id,modifiers,credits) VALUES($1,'meal','meal','Meal','sq-meal',$2,1)",[redemption,JSON.stringify(mods)])).rejects.toThrow()}
  for(const square of [" square","square ","square id","square\u0001id"]){const redemption=(await owner.query<{id:string}>("INSERT INTO downtown_u_redemptions(student_id,credits,idempotency_key) VALUES($1,1,$2) RETURNING id",[p.student,`bad-square-${createHash('sha256').update(square).digest('hex').slice(0,12)}`])).rows[0].id;await expect(owner.query("INSERT INTO downtown_u_reservation_snapshots(redemption_id,meal_rule_id,meal_public_id,meal_display_name,meal_square_catalog_object_id,credits) VALUES($1,'meal','meal','Meal',$2,1)",[redemption,square])).rejects.toThrow()}
  const valid=await reserve(p,"canonical_valid_key");expect((await owner.query("SELECT downtown_u_valid_modifier_snapshot(modifiers) valid FROM downtown_u_reservation_snapshots WHERE redemption_id=$1",[valid.id])).rows[0].valid).toBe(true);await expect(runtime.query("INSERT INTO downtown_u_reservation_snapshots(redemption_id,meal_rule_id,meal_public_id,meal_display_name,meal_square_catalog_object_id,credits) VALUES(gen_random_uuid(),'meal','meal','Meal','sq',1)")).rejects.toMatchObject({code:"42501"});await expect(owner.query("TRUNCATE downtown_u_reservation_snapshots")).rejects.toThrow(/immutable/)});
 it("takes reservation time only after the trusted meal rule lock",async()=>{const p=await principal("rule-lock");const blocker=await owner.connect();let committed=false;try{await blocker.query("BEGIN");await blocker.query("UPDATE downtown_u_meal_rules SET available_until=clock_timestamp()-interval '1 second' WHERE id='meal'");const pending=reserve(p,"rule_lock_reserve_key");await new Promise(resolve=>setTimeout(resolve,120));await blocker.query("COMMIT");committed=true;await expect(pending).rejects.toThrow(/invalid request/)}finally{if(!committed)await blocker.query("ROLLBACK").catch(()=>undefined);blocker.release();await owner.query("UPDATE downtown_u_meal_rules SET available_until=NULL WHERE id='meal'")}});
 it("rechecks a credential after waiting on its session lock",async()=>{const original=await principal("session-lock");const short:Principal={student:original.student,session:createHash("sha256").update("short-session-lock").digest("base64url"),digest:createHash("sha256").update("short-token-lock").digest()};await owner.query("INSERT INTO downtown_u_auth_sessions(session_id,student_id,verifier_version,token_digest,expires_at) VALUES($1,$2,1,$3,clock_timestamp()+interval '150 milliseconds')",[short.session,short.student,short.digest]);const blocker=await owner.connect();let committed=false;try{await blocker.query("BEGIN");await blocker.query("SELECT 1 FROM downtown_u_auth_sessions WHERE session_id=$1 FOR UPDATE",[short.session]);const pending=runtime.query("SELECT payload FROM downtown_u_student_me($1,$2::smallint,$3::bytea)",args(short));await new Promise(resolve=>setTimeout(resolve,220));await blocker.query("COMMIT");committed=true;await expect(pending).rejects.toThrow(/invalid principal/)}finally{if(!committed)await blocker.query("ROLLBACK").catch(()=>undefined);blocker.release()}});
 it("rechecks cancellation expiry after waiting on the redemption lock",async()=>{const p=await principal("cancel-lock");const reservation=await reserve(p,"cancel_lock_reserve");const blocker=await owner.connect();let committed=false;try{await blocker.query("BEGIN");await blocker.query("UPDATE downtown_u_redemptions SET expires_at=clock_timestamp()+interval '150 milliseconds' WHERE id=$1",[reservation.id]);const pending=reverse(p,String(reservation.id),"cancel_lock_key_123");await new Promise(resolve=>setTimeout(resolve,220));await blocker.query("COMMIT");committed=true;await expect(pending).rejects.toThrow(/expired reservation/)}finally{if(!committed)await blocker.query("ROLLBACK").catch(()=>undefined);blocker.release()}expect((await jobs.query("SELECT downtown_u_reverse_expired_reservations(100) n")).rows[0].n).toBe(1)});
 it("takes expiry-job time after the advisory lock",async()=>{const p=await principal("advisory-lock");const reservation=await reserve(p,"advisory_lock_reserve");await owner.query("UPDATE downtown_u_redemptions SET expires_at=clock_timestamp()+interval '150 milliseconds' WHERE id=$1",[reservation.id]);const blocker=await owner.connect();let committed=false;try{await blocker.query("BEGIN");await blocker.query("SELECT pg_advisory_xact_lock(hashtextextended('downtown_u_expiry_job',0))");const pending=jobs.query("SELECT downtown_u_reverse_expired_reservations(1) n");await new Promise(resolve=>setTimeout(resolve,220));await blocker.query("COMMIT");committed=true;expect((await pending).rows[0].n).toBe(1)}finally{if(!committed)await blocker.query("ROLLBACK").catch(()=>undefined);blocker.release()}expect((await owner.query("SELECT status FROM downtown_u_redemptions WHERE id=$1",[reservation.id])).rows[0].status).toBe("reversed")});
 it("makes a shared reserve key global without cross-student effects",async()=>{const a=await principal("collision-a");const b=await principal("collision-b");const settled=await Promise.allSettled([reserve(a,"global_collision_key"),reserve(b,"global_collision_key")]);expect(settled.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(settled.filter(x=>x.status==="rejected")).toHaveLength(1);const balances=(await owner.query("SELECT id,credit_balance FROM downtown_u_students WHERE id=ANY($1::uuid[]) ORDER BY id",[[a.student,b.student]])).rows.map(x=>x.credit_balance).sort();expect(balances).toEqual([3,5]);expect((await owner.query("SELECT count(*)::int n FROM downtown_u_redemptions WHERE idempotency_key='global_collision_key'")).rows[0].n).toBe(1)});
 it("validates expiry limits and processes only the deterministic earliest row",async()=>{const p=await principal("expiry-limit",5);const first=await reserve(p,"expiry_limit_first","other");const second=await reserve(p,"expiry_limit_second","other");await owner.query("UPDATE downtown_u_redemptions SET expires_at=CASE id WHEN $1 THEN clock_timestamp()-interval '2 seconds' ELSE clock_timestamp()-interval '1 second' END WHERE id=ANY($2::uuid[])",[first.id,[first.id,second.id]]);await expect(jobs.query("SELECT downtown_u_reverse_expired_reservations(0)")).rejects.toThrow(/invalid request/);await expect(jobs.query("SELECT downtown_u_reverse_expired_reservations(101)")).rejects.toThrow(/invalid request/);expect((await jobs.query("SELECT downtown_u_reverse_expired_reservations(1) n")).rows[0].n).toBe(1);expect((await owner.query("SELECT status FROM downtown_u_redemptions WHERE id=$1",[first.id])).rows[0].status).toBe("reversed");expect((await owner.query("SELECT status FROM downtown_u_redemptions WHERE id=$1",[second.id])).rows[0].status).toBe("reserved");expect((await jobs.query("SELECT downtown_u_reverse_expired_reservations(100) n")).rows[0].n).toBe(1)});
 it("allows exactly twenty reservations per rate window without charging failures",async()=>{const p=await principal("reserve-rate",0);await expect(reserve(p,"rate_invalid_before","inactive")).rejects.toThrow(/invalid request/);await expect(reserve(p,"rate_insufficient_before")).rejects.toThrow(/insufficient credits/);for(let i=0;i<4;i++)await grantFive(p,`reserve-rate-${i}`);for(let i=0;i<20;i++)await expect(reserve(p,`reserve_rate_key_${String(i).padStart(2,"0")}`,"other")).resolves.toMatchObject({credits:1});await expect(reserve(p,"reserve_rate_key_20","other")).rejects.toThrow(/rate limited/);expect((await owner.query("SELECT count(*)::int n FROM downtown_u_reservation_snapshots s JOIN downtown_u_redemptions r ON r.id=s.redemption_id WHERE r.student_id=$1",[p.student])).rows[0].n).toBe(20)});
 it("allows exactly ten student cancellation reversals per rate window",async()=>{const p=await principal("cancel-rate");for(let i=0;i<2;i++)await grantFive(p,`cancel-rate-${i}`);const reservations=[];for(let i=0;i<11;i++)reservations.push(await reserve(p,`cancel_rate_res_${String(i).padStart(2,"0")}`,"other"));for(let i=0;i<10;i++)await expect(reverse(p,String(reservations[i].id),`cancel_rate_key_${String(i).padStart(2,"0")}`)).resolves.toMatchObject({status:"reversed"});await expect(reverse(p,String(reservations[10].id),"cancel_rate_key_10")).rejects.toThrow(/rate limited/);expect((await owner.query("SELECT count(*)::int n FROM downtown_u_credit_transactions WHERE student_id=$1 AND transaction_type='redemption_reversal' AND reason='student_cancelled'",[p.student])).rows[0].n).toBe(10)});
 async function jobBodyDrift(signature:string){const definition=(await owner.query<{definition:string}>("SELECT pg_get_functiondef($1::regprocedure) definition",[signature])).rows[0].definition;const name=signature.slice(0,signature.indexOf("("));await owner.query(`CREATE OR REPLACE FUNCTION ${signature} RETURNS trigger LANGUAGE plpgsql AS 'BEGIN RETURN NEW; END'`);await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);await owner.query(definition);await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined();expect(name).toMatch(/^downtown_u_/)}
 it("detects transitive ledger trigger body drift in job preflight",async()=>{await jobBodyDrift("downtown_u_apply_credit_transaction()");await jobBodyDrift("downtown_u_require_trusted_purchase_grant()")});
 it("detects expiry body, ACL, and overload drift in job preflight",async()=>{const signature="downtown_u_reverse_expired_reservations(integer)";const definition=(await owner.query<{definition:string}>("SELECT pg_get_functiondef($1::regprocedure) definition",[signature])).rows[0].definition;await owner.query("CREATE OR REPLACE FUNCTION downtown_u_reverse_expired_reservations(requested_limit integer) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS 'BEGIN RETURN 0; END'");await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);await owner.query(definition);await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined();await owner.query("REVOKE EXECUTE ON FUNCTION downtown_u_reverse_expired_reservations(integer) FROM downtown_u_jobs");await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);await owner.query("GRANT EXECUTE ON FUNCTION downtown_u_reverse_expired_reservations(integer) TO downtown_u_jobs");await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined();await owner.query("CREATE FUNCTION downtown_u_reverse_expired_reservations(integer,text) RETURNS integer LANGUAGE plpgsql SET search_path=pg_catalog AS 'BEGIN RETURN 0; END'");await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);await owner.query("DROP FUNCTION downtown_u_reverse_expired_reservations(integer,text)");await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined()});
 async function jobRelationDrift(sql:string,restore:string){await owner.query(sql);await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);await owner.query(restore);await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined()}
 it("detects and recovers rewrite-rule drift in job preflight",()=>jobRelationDrift("CREATE RULE downtown_u_drift_rule AS ON INSERT TO downtown_u_redemptions DO ALSO NOTHING","DROP RULE downtown_u_drift_rule ON downtown_u_redemptions"));
 it("detects and recovers RLS flags and policy drift in job preflight",async()=>{await jobRelationDrift("ALTER TABLE downtown_u_meal_rules ENABLE ROW LEVEL SECURITY","ALTER TABLE downtown_u_meal_rules DISABLE ROW LEVEL SECURITY");await jobRelationDrift("ALTER TABLE downtown_u_meal_rules FORCE ROW LEVEL SECURITY","ALTER TABLE downtown_u_meal_rules NO FORCE ROW LEVEL SECURITY");await jobRelationDrift("CREATE POLICY downtown_u_drift_policy ON downtown_u_meal_rules FOR SELECT TO downtown_u_runtime USING (active)","DROP POLICY downtown_u_drift_policy ON downtown_u_meal_rules")});
 it("detects Downtown sequences with and without effective job privileges",async()=>{
  await owner.query("CREATE SEQUENCE public.downtown_u_drift_sequence");
  await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);
  await expect(assertDowntownURuntimeIdentity(runtime as never)).rejects.toThrow(/Unsafe/);
  await owner.query("GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.downtown_u_drift_sequence TO downtown_u_jobs");
  await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).rejects.toThrow(/Unsafe/);
  await owner.query("DROP SEQUENCE public.downtown_u_drift_sequence");
  await expect(assertDowntownUJobRuntimeIdentity(jobs as never)).resolves.toBeUndefined();
  await expect(assertDowntownURuntimeIdentity(runtime as never)).resolves.toBeUndefined();
 });
 it("detects and recovers relation-option drift in job preflight",()=>jobRelationDrift("ALTER TABLE downtown_u_meal_rules SET (fillfactor=70)","ALTER TABLE downtown_u_meal_rules RESET (fillfactor)"));
 it("detects and recovers trigger enabled and event drift in job preflight",async()=>{await jobRelationDrift("ALTER TABLE downtown_u_reservation_snapshots DISABLE TRIGGER downtown_u_reservation_snapshots_immutable","ALTER TABLE downtown_u_reservation_snapshots ENABLE TRIGGER downtown_u_reservation_snapshots_immutable");await jobRelationDrift("CREATE TRIGGER downtown_u_drift_event BEFORE INSERT ON downtown_u_reservation_snapshots FOR EACH ROW EXECUTE FUNCTION downtown_u_reject_reservation_snapshot_mutation()","DROP TRIGGER downtown_u_drift_event ON downtown_u_reservation_snapshots")});
 async function drift(sql:string,restore:string){await owner.query(sql);await expect(assertDowntownURuntimeIdentity(runtime as never)).rejects.toThrow(/Unsafe/);await owner.query(restore);await expect(assertDowntownURuntimeIdentity(runtime as never)).resolves.toBeUndefined()}
 async function webTriggerBodyDrift(signature:string){const definition=(await owner.query<{definition:string}>("SELECT pg_get_functiondef($1::regprocedure) definition",[signature])).rows[0].definition;await owner.query(`CREATE OR REPLACE FUNCTION ${signature} RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS 'BEGIN RETURN NEW; END'`);await expect(assertDowntownURuntimeIdentity(runtime as never)).rejects.toThrow(/Unsafe/);await owner.query(definition);await expect(assertDowntownURuntimeIdentity(runtime as never)).resolves.toBeUndefined()}
 it("detects portal and historical authentication body drift",async()=>{await webTriggerBodyDrift("downtown_u_reject_reservation_snapshot_mutation()");await webTriggerBodyDrift("downtown_u_auth_protect_session()")});
 it("detects representative default, nullability, type, and renamed-trigger drift",async()=>{await drift("ALTER TABLE downtown_u_reservation_snapshots ALTER COLUMN modifiers DROP DEFAULT","ALTER TABLE downtown_u_reservation_snapshots ALTER COLUMN modifiers SET DEFAULT '[]'::jsonb");await drift("ALTER TABLE downtown_u_reservation_snapshots ALTER COLUMN meal_square_catalog_object_id DROP NOT NULL","ALTER TABLE downtown_u_reservation_snapshots ALTER COLUMN meal_square_catalog_object_id SET NOT NULL");await drift("ALTER TABLE downtown_u_reservation_snapshots ALTER COLUMN meal_square_catalog_object_id TYPE varchar(192)","ALTER TABLE downtown_u_reservation_snapshots ALTER COLUMN meal_square_catalog_object_id TYPE text");await drift("ALTER TRIGGER downtown_u_reservation_snapshots_immutable ON downtown_u_reservation_snapshots RENAME TO drift_snapshot_trigger","ALTER TRIGGER drift_snapshot_trigger ON downtown_u_reservation_snapshots RENAME TO downtown_u_reservation_snapshots_immutable")});
 it("detects and recovers function volatility drift",()=>drift("ALTER FUNCTION downtown_u_student_meals(text,smallint,bytea) STABLE","ALTER FUNCTION downtown_u_student_meals(text,smallint,bytea) VOLATILE"));
 it("detects and recovers function security drift",()=>drift("ALTER FUNCTION downtown_u_student_meals(text,smallint,bytea) SECURITY INVOKER","ALTER FUNCTION downtown_u_student_meals(text,smallint,bytea) SECURITY DEFINER"));
 it("detects and recovers function configuration drift",()=>drift("ALTER FUNCTION downtown_u_student_meals(text,smallint,bytea) RESET search_path","ALTER FUNCTION downtown_u_student_meals(text,smallint,bytea) SET search_path=pg_catalog"));
 it("detects and recovers function ACL drift",()=>drift("REVOKE EXECUTE ON FUNCTION downtown_u_student_meals(text,smallint,bytea) FROM downtown_u_runtime","GRANT EXECUTE ON FUNCTION downtown_u_student_meals(text,smallint,bytea) TO downtown_u_runtime"));
 it("detects and recovers overload drift",()=>drift("CREATE FUNCTION public.downtown_u_student_meals(text) RETURNS void LANGUAGE plpgsql SET search_path=pg_catalog AS 'BEGIN END'","DROP FUNCTION public.downtown_u_student_meals(text)"));
 it("detects and recovers portal column drift",()=>drift("ALTER TABLE downtown_u_meal_rules ADD COLUMN drift text","ALTER TABLE downtown_u_meal_rules DROP COLUMN drift"));
 it("detects and recovers portal constraint drift",()=>drift("ALTER TABLE downtown_u_meal_rules ADD CONSTRAINT drift_check CHECK (base_credits>0)","ALTER TABLE downtown_u_meal_rules DROP CONSTRAINT drift_check"));
 it("detects and recovers portal index drift",()=>drift("CREATE INDEX drift_index ON downtown_u_meal_rules(display_name)","DROP INDEX drift_index"));
 it("detects and recovers portal trigger drift",()=>drift("ALTER TABLE downtown_u_reservation_snapshots DISABLE TRIGGER downtown_u_reservation_snapshots_immutable","ALTER TABLE downtown_u_reservation_snapshots ENABLE TRIGGER downtown_u_reservation_snapshots_immutable"));
 it("detects and recovers portal ACL drift",()=>drift(`GRANT SELECT ON downtown_u_meal_rules TO ${q(login)}`,`REVOKE SELECT ON downtown_u_meal_rules FROM ${q(login)}`));
 it("passes pristine web and job identities when an alternate role owns and migrates the database",async()=>{const altOwner=`downtown_u_alt_owner_${suffix}`;const altDatabase=`downtown_u_alt_${suffix}`;const altWebLogin=`downtown_u_alt_web_${suffix}`;const altJobLogin=`downtown_u_alt_job_${suffix}`;let migrationPool:Pool|undefined;let altRuntime:Pool|undefined;let altJobs:Pool|undefined;try{await admin.query(`CREATE ROLE ${q(altOwner)} NOLOGIN CREATEROLE`);await admin.query(`CREATE DATABASE ${q(altDatabase)} OWNER ${q(altOwner)}`);const parsed=new URL(baseUrl!);parsed.pathname=`/${altDatabase}`;parsed.username="";parsed.password="";migrationPool=new Pool({connectionString:parsed.toString(),max:1});const client=await migrationPool.connect();try{await client.query(`SET ROLE ${q(altOwner)}`);for(const migration of migrations)await client.query(migration);await client.query("RESET ROLE")}finally{client.release()}await admin.query(`ALTER ROLE ${q(altOwner)} NOCREATEROLE`);await admin.query(`CREATE ROLE ${q(altWebLogin)} LOGIN`);await admin.query(`CREATE ROLE ${q(altJobLogin)} LOGIN`);await admin.query(`GRANT downtown_u_runtime TO ${q(altWebLogin)}`);await admin.query(`GRANT downtown_u_jobs TO ${q(altJobLogin)}`);parsed.username=altWebLogin;altRuntime=new Pool({connectionString:parsed.toString(),max:1});parsed.username=altJobLogin;altJobs=new Pool({connectionString:parsed.toString(),max:1});await expect(assertDowntownURuntimeIdentity(altRuntime as never)).resolves.toBeUndefined();await expect(assertDowntownUJobRuntimeIdentity(altJobs as never)).resolves.toBeUndefined()}finally{await altRuntime?.end();await altJobs?.end();await migrationPool?.end();await admin.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1",[altDatabase]);await admin.query(`DROP DATABASE IF EXISTS ${q(altDatabase)}`);await admin.query(`DROP ROLE IF EXISTS ${q(altWebLogin)}`);await admin.query(`DROP ROLE IF EXISTS ${q(altJobLogin)}`);await admin.query(`DROP ROLE IF EXISTS ${q(altOwner)}`)}});
});
