import "@testing-library/jest-dom/vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import DowntownUCheckout from "../DowntownUCheckout";

const attemptId="11111111-1111-4111-8111-111111111111";
const json=(body:unknown,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...headers}});
type FakeCard={attach:ReturnType<typeof vi.fn>;tokenize:ReturnType<typeof vi.fn>;destroy:ReturnType<typeof vi.fn>};
function installSquare(tokens=["cnon:one"]){let index=0;const card:FakeCard={attach:vi.fn().mockResolvedValue(undefined),tokenize:vi.fn().mockImplementation(async()=>({status:"OK",token:tokens[Math.min(index++,tokens.length-1)]})),destroy:vi.fn().mockResolvedValue(undefined)};const payments=vi.fn(()=>({card:vi.fn().mockResolvedValue(card)}));Object.defineProperty(window,"Square",{configurable:true,writable:true,value:{payments}});return {card,payments};}
function secure(value=true){Object.defineProperty(window,"isSecureContext",{configurable:true,value});}
async function ready(eligibilityConfirmed=true){const square=installSquare();const fetcher=vi.fn().mockResolvedValue(json({applicationId:"sq-app",locationId:"LPPWSSV03BHK8"}));vi.stubGlobal("fetch",fetcher);render(<DowntownUCheckout planId="flex-5" eligibilityConfirmed={eligibilityConfirmed}/>);await waitFor(()=>expect(square.card.attach).toHaveBeenCalledWith("#downtown-u-card"));return {...square,fetcher};}
async function email(value="student@example.edu"){fireEvent.change(screen.getByLabelText("Student email"),{target:{value}});await act(async()=>{});}

beforeEach(()=>{secure();vi.spyOn(globalThis.crypto,"randomUUID").mockReturnValue("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa");});
afterEach(()=>{cleanup();sessionStorage.clear();vi.unstubAllGlobals();vi.restoreAllMocks();delete (window as Window & {Square?:unknown}).Square;document.querySelectorAll("script[data-downtown-u-square]").forEach(node=>node.remove());vi.useRealTimers();});

describe("DowntownUCheckout embedded Square lifecycle",()=>{
 it("fails closed in an insecure context without fetching or exposing a hosted redirect",async()=>{secure(false);const fetcher=vi.fn();vi.stubGlobal("fetch",fetcher);render(<DowntownUCheckout planId="flex-5" eligibilityConfirmed/>);expect(await screen.findByRole("alert")).toHaveTextContent("No payment has been taken");expect(fetcher).not.toHaveBeenCalled();expect(document.querySelector("a[href*='square']")).toBeNull();});

 it("loads strict config with a bodyless secured GET, uses existing SDK, attaches, and destroys on cleanup",async()=>{const {card,payments,fetcher}=await ready();expect(fetcher).toHaveBeenNthCalledWith(1,"/api/downtown-u/checkout-config",expect.objectContaining({method:"GET",credentials:"same-origin",cache:"no-store",referrerPolicy:"no-referrer",signal:expect.any(AbortSignal)}));expect(fetcher.mock.calls[0][1]).not.toHaveProperty("body");expect(payments).toHaveBeenCalledWith("sq-app","LPPWSSV03BHK8");cleanup();await waitFor(()=>expect(card.destroy).toHaveBeenCalledOnce());});

 it.each([
  ["extra config property",{applicationId:"sq-app",locationId:"LPPWSSV03BHK8",secret:"no"},{}],
  ["bad identifier",{applicationId:"bad app",locationId:"LPPWSSV03BHK8"},{}],
  ["wrong content type",{applicationId:"sq-app",locationId:"LPPWSSV03BHK8"},{"Content-Type":"text/html"}],
  ["oversized declaration",{applicationId:"sq-app",locationId:"LPPWSSV03BHK8"},{"Content-Length":"4097"}],
 ])("rejects %s before initializing Square",async(_label,body,headers)=>{const square=installSquare();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json(body,200,headers)));render(<DowntownUCheckout planId="flex-5" eligibilityConfirmed/>);expect(await screen.findByRole("alert")).toHaveTextContent("unavailable");expect(square.payments).not.toHaveBeenCalled();});

 it("injects the pinned Square SDK and handles load failure",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json({applicationId:"sq-app",locationId:"LPPWSSV03BHK8"})));render(<DowntownUCheckout planId="flex-5" eligibilityConfirmed/>);const script=await waitFor(()=>{const node=document.querySelector<HTMLScriptElement>('script[data-downtown-u-square="1"]');expect(node).not.toBeNull();return node!;});expect(script.src).toBe("https://web.squarecdn.com/v1/square.js");expect(script.crossOrigin).toBe("anonymous");fireEvent.error(script);expect(await screen.findByRole("alert")).toHaveTextContent("unavailable");});

 it("destroys a card instance when attach fails",async()=>{const square=installSquare();square.card.attach.mockRejectedValueOnce(new Error("attach"));vi.stubGlobal("fetch",vi.fn().mockResolvedValue(json({applicationId:"sq-app",locationId:"LPPWSSV03BHK8"})));render(<DowntownUCheckout planId="flex-5" eligibilityConfirmed/>);expect(await screen.findByRole("alert")).toHaveTextContent("unavailable");expect(square.card.destroy).toHaveBeenCalledOnce();});

 it("enforces eligibility/email and sends the exact server-minimal body for activated payment",async()=>{const {card,fetcher}=await ready(false);const button=screen.getByRole("button",{name:"Pay securely with Square"});expect(button).toBeDisabled();await email();expect(button).toBeDisabled();cleanup();
  const setup=await ready(true);await email();setup.fetcher.mockResolvedValueOnce(json({attemptId,state:"activated"}));fireEvent.click(screen.getByRole("button"));expect(await screen.findByText("Payment confirmed and plan activated.")).toBeInTheDocument();expect(setup.card.tokenize).toHaveBeenCalledOnce();const [,init]=setup.fetcher.mock.calls[1];expect(init).toEqual(expect.objectContaining({method:"POST",credentials:"same-origin",cache:"no-store",referrerPolicy:"no-referrer",headers:{"Content-Type":"application/json"}}));expect(JSON.parse(String(init.body))).toEqual({planId:"flex-5",sourceId:"cnon:one",email:"student@example.edu",eligibilityConfirmed:true,idempotencyKey:"aaaaaaaaaaaa4aaa8aaaaaaaaaaaaaaa"});});

 it("reports tokenization failure without calling checkout",async()=>{const {card,fetcher}=await ready();card.tokenize.mockResolvedValueOnce({status:"ERROR",errors:[{detail:"private"}]});await email();fireEvent.click(screen.getByRole("button"));expect(await screen.findByRole("alert")).toHaveTextContent("Check your card details");expect(fetcher).toHaveBeenCalledOnce();});

 it("keeps source and key stable after an ambiguous response so retry cannot duplicate payment",async()=>{const {card,fetcher}=await ready();await email();fetcher.mockRejectedValueOnce(new Error("network private"));fireEvent.click(screen.getByRole("button"));expect(await screen.findByRole("alert")).toHaveTextContent("same payment attempt");fetcher.mockResolvedValueOnce(json({attemptId,state:"paid"}));fireEvent.click(screen.getByRole("button"));expect(await screen.findByText(/pending activation/)).toBeInTheDocument();expect(card.tokenize).toHaveBeenCalledOnce();const bodies=fetcher.mock.calls.slice(1).map((call)=>JSON.parse(String(call[1].body)));expect(bodies[0]).toEqual(bodies[1]);});

 it("retokenizes and creates a new key only after a definitive decline",async()=>{vi.mocked(globalThis.crypto.randomUUID).mockReset().mockReturnValueOnce("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa").mockReturnValueOnce("bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb");const {card,fetcher}=await ready();card.tokenize.mockResolvedValueOnce({status:"OK",token:"cnon:first"}).mockResolvedValueOnce({status:"OK",token:"cnon:second"});await email();fetcher.mockResolvedValueOnce(json({attemptId,state:"failed"},402));fireEvent.click(screen.getByRole("button"));expect(await screen.findByRole("alert")).toHaveTextContent("declined");fetcher.mockResolvedValueOnce(json({attemptId,state:"paid"}));fireEvent.click(screen.getByRole("button"));await screen.findByText(/pending activation/);const [first,second]=fetcher.mock.calls.slice(1).map(call=>JSON.parse(String(call[1].body)));expect(first.sourceId).toBe("cnon:first");expect(second.sourceId).toBe("cnon:second");expect(second.idempotencyKey).not.toBe(first.idempotencyKey);});

 it("locks email/card and keeps the submitted snapshot when an ambiguous request is retried",async()=>{const {card,fetcher}=await ready();await email("one@example.edu");fetcher.mockRejectedValueOnce(new Error("ambiguous"));fireEvent.click(screen.getByRole("button"));await screen.findByRole("alert");expect(screen.getByLabelText("Student email")).toBeDisabled();expect(screen.getByLabelText("Secure card details")).toHaveAttribute("aria-disabled","true");expect(JSON.parse(sessionStorage.getItem("proper-cuisine:downtown-u:checkout:v1")!)).not.toHaveProperty("email");fetcher.mockResolvedValueOnce(json({attemptId,state:"paid"}));fireEvent.click(screen.getByRole("button",{name:"Resume same payment attempt"}));await screen.findByText(/pending activation/);expect(card.tokenize).toHaveBeenCalledOnce();const bodies=fetcher.mock.calls.slice(1).map(call=>JSON.parse(String(call[1].body)));expect(bodies[1]).toEqual(bodies[0]);});

 it("recovers an unresolved attempt after remount by polling only, without persisting or recreating a source",async()=>{sessionStorage.setItem("proper-cuisine:downtown-u:checkout:v1",JSON.stringify({v:1,attemptId,idempotencyKey:"aaaaaaaaaaaa4aaa8aaaaaaaaaaaaaaa",planId:"flex-5",unresolved:true}));const square=installSquare();const fetcher=vi.fn().mockResolvedValueOnce(json({applicationId:"sq-app",locationId:"LPPWSSV03BHK8"})).mockResolvedValueOnce(json({state:"paid"}));vi.stubGlobal("fetch",fetcher);vi.useFakeTimers();render(<DowntownUCheckout planId="scholar-10" eligibilityConfirmed/>);expect(screen.getByLabelText("Student email")).toBeDisabled();expect(screen.getByRole("button")).toBeDisabled();await act(async()=>{await Promise.resolve();await Promise.resolve();await vi.advanceTimersByTimeAsync(250);});expect(screen.getByText(/pending activation/)).toBeInTheDocument();expect(square.card.tokenize).not.toHaveBeenCalled();expect(fetcher.mock.calls.filter(call=>call[1]?.method==="POST")).toHaveLength(0);expect(sessionStorage.getItem("proper-cuisine:downtown-u:checkout:v1")).not.toContain("source");});

 it("keeps paid recovery locked but clears recovery only on definitive failed status",async()=>{sessionStorage.setItem("proper-cuisine:downtown-u:checkout:v1",JSON.stringify({v:1,attemptId,idempotencyKey:"aaaaaaaaaaaa4aaa8aaaaaaaaaaaaaaa",planId:"flex-5",unresolved:false}));const first=await ready();expect(screen.getByLabelText("Student email")).toBeDisabled();expect(screen.getByRole("button")).toBeDisabled();cleanup();sessionStorage.setItem("proper-cuisine:downtown-u:checkout:v1",JSON.stringify({v:1,attemptId,idempotencyKey:"aaaaaaaaaaaa4aaa8aaaaaaaaaaaaaaa",planId:"flex-5",unresolved:true}));const square=installSquare();const fetcher=vi.fn().mockResolvedValueOnce(json({applicationId:"sq-app",locationId:"LPPWSSV03BHK8"})).mockResolvedValueOnce(json({state:"failed"}));vi.stubGlobal("fetch",fetcher);vi.useFakeTimers();render(<DowntownUCheckout planId="flex-5" eligibilityConfirmed/>);await act(async()=>{await Promise.resolve();await Promise.resolve();await vi.advanceTimersByTimeAsync(250);await Promise.resolve();});expect(screen.getByLabelText("Student email")).not.toBeDisabled();expect(sessionStorage.getItem("proper-cuisine:downtown-u:checkout:v1")).toBeNull();expect(first.card.tokenize).not.toHaveBeenCalled();expect(square.card.tokenize).not.toHaveBeenCalled();});

 it("polls an ambiguous attempt and stops immediately on paid status",async()=>{const {fetcher}=await ready();await email();vi.useFakeTimers();fetcher.mockResolvedValueOnce(json({attemptId,state:"operator_review"},202)).mockResolvedValueOnce(json({state:"paid"}));fireEvent.click(screen.getByRole("button"));await act(async()=>{await Promise.resolve();await Promise.resolve();await vi.advanceTimersByTimeAsync(250);});expect(screen.getByText(/pending activation/)).toBeInTheDocument();expect(fetcher).toHaveBeenCalledTimes(3);expect(fetcher.mock.calls[2][0]).toBe(`/api/downtown-u/checkout?id=${attemptId}`);});

 it("offers only a same-attempt resume after status polling stays unresolved",async()=>{const {card,fetcher}=await ready();await email();vi.useFakeTimers();fetcher.mockResolvedValueOnce(json({attemptId,state:"payment_created"},202)).mockResolvedValue(json({state:"payment_created"}));fireEvent.click(screen.getByRole("button"));await act(async()=>{await Promise.resolve();await vi.advanceTimersByTimeAsync(8000);});expect(screen.getByRole("button",{name:"Resume same payment attempt"})).toBeEnabled();expect(screen.getByLabelText("Student email")).toBeDisabled();expect(card.tokenize).toHaveBeenCalledOnce();});

 it("has labelled email/card controls, live status, and no hosted checkout navigation",async()=>{await ready();expect(screen.getByLabelText("Student email")).toHaveAttribute("required");expect(screen.getByLabelText("Secure card details")).toBeInTheDocument();expect(screen.getByText(/never receives your card number/)).toBeInTheDocument();expect(document.querySelector("form")).toBeNull();expect(document.querySelector("a[href*='checkout']")).toBeNull();});
});
