import { useEffect, useRef, useState } from "react";
import type { DowntownUPlanId } from "@/config/downtownUPaymentLinks";

type Card = { attach(selector:string):Promise<void>; tokenize():Promise<{status:string;token?:string;errors?:unknown}>; destroy():Promise<void> };
type Payments = { card():Promise<Card> };
type SquareWindow = Window & { Square?: { payments(applicationId:string,locationId:string):Payments } };
type State = "loading"|"ready"|"submitting"|"pending"|"paid"|"unavailable"|"error";
type CheckoutState = "started"|"order_created"|"payment_created"|"paid"|"activated"|"operator_review"|"failed";
type Recovery = { v:1; attemptId:string|null; idempotencyKey:string; planId:DowntownUPlanId; unresolved:boolean };
const SDK = "https://web.squarecdn.com/v1/square.js";
const STORAGE_KEY = "proper-cuisine:downtown-u:checkout:v1";
const RESPONSE_LIMIT = 4096;
const REQUEST_TIMEOUT = 10_000;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const KEY = /^[A-Za-z0-9_-]{16,45}$/;
const PLANS: DowntownUPlanId[] = ["flex-5","scholar-10","resident-20","semester-40"];
function newKey():string { return globalThis.crypto.randomUUID().replace(/-/g, ""); }
function plain(value:unknown,keys:string[]):Record<string,unknown>|null { if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype||Object.keys(value).sort().join("\0")!==[...keys].sort().join("\0"))return null;return value as Record<string,unknown>; }
function readRecovery():Recovery|null { try { const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return null;const o=plain(JSON.parse(raw) as unknown,["v","attemptId","idempotencyKey","planId","unresolved"]);if(!o||o.v!==1||(o.attemptId!==null&&(typeof o.attemptId!=="string"||!UUID.test(o.attemptId)))||typeof o.idempotencyKey!=="string"||!KEY.test(o.idempotencyKey)||typeof o.planId!=="string"||!PLANS.includes(o.planId as DowntownUPlanId)||typeof o.unresolved!=="boolean")throw new Error();return o as Recovery;}catch{try{sessionStorage.removeItem(STORAGE_KEY);}catch{return null;}return null;} }
function persistRecovery(value:Recovery):boolean { try { const encoded=JSON.stringify(value);sessionStorage.setItem(STORAGE_KEY,encoded);return sessionStorage.getItem(STORAGE_KEY)===encoded;}catch{return false;} }
function clearRecovery():void { try{sessionStorage.removeItem(STORAGE_KEY);}catch{/* Fail closed in memory even if unavailable. */} }
async function boundedJson(response:Response):Promise<unknown>{
 if(!/^application\/json(?:\s*;\s*charset\s*=\s*(?:utf-8|"utf-8"))?$/i.test(response.headers.get("content-type")??""))throw new Error("invalid response");
 if(!response.body)throw new Error("invalid response");const reader=response.body.getReader();const declared=response.headers.get("content-length");let size=0;const chunks:Uint8Array[]=[];try{if(declared!==null&&(!/^\d+$/.test(declared)||Number(declared)>RESPONSE_LIMIT)){await reader.cancel();throw new Error("invalid response");}while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>RESPONSE_LIMIT){await reader.cancel();throw new Error("invalid response");}chunks.push(value);}}finally{reader.releaseLock();}
 const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.byteLength;}return JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(all)) as unknown;
}
async function requestJson(url:string,init:RequestInit={},parent?:AbortSignal):Promise<{response:Response;data:unknown}>{const controller=new AbortController();const abort=()=>controller.abort();parent?.addEventListener("abort",abort,{once:true});const timer=setTimeout(abort,REQUEST_TIMEOUT);try{const response=await fetch(url,{credentials:"same-origin",cache:"no-store",referrerPolicy:"no-referrer",...init,signal:controller.signal});return {response,data:await boundedJson(response)};}finally{clearTimeout(timer);parent?.removeEventListener("abort",abort);}}
function parseConfig(value:unknown):{applicationId:string;locationId:string}|null { const o=plain(value,["applicationId","locationId"]);if(!o)return null;return typeof o.applicationId==="string"&&/^[A-Za-z0-9_-]{1,192}$/.test(o.applicationId)&&typeof o.locationId==="string"&&/^[A-Za-z0-9_-]{1,192}$/.test(o.locationId)?o as {applicationId:string;locationId:string}:null; }
function parseCheckout(value:unknown):{attemptId:string;state:CheckoutState}|null { const o=plain(value,["attemptId","state"]);if(!o||typeof o.attemptId!=="string"||!UUID.test(o.attemptId)||typeof o.state!=="string"||!["started","order_created","payment_created","paid","activated","operator_review","failed"].includes(o.state))return null;return o as {attemptId:string;state:CheckoutState}; }
function parseStatus(value:unknown):{state:CheckoutState}|null { const o=plain(value,["state"]);if(!o||typeof o.state!=="string"||!["started","order_created","payment_created","paid","activated","operator_review","failed"].includes(o.state))return null;return o as {state:CheckoutState}; }
async function loadSquare(signal:{active:boolean}):Promise<void>{if((window as SquareWindow).Square)return;let script=document.querySelector<HTMLScriptElement>(`script[src="${SDK}"]`);if(!script){script=document.createElement("script");script.src=SDK;script.async=true;script.crossOrigin="anonymous";script.dataset.downtownUSquare="1";document.head.append(script);}await new Promise<void>((resolve,reject)=>{if((window as SquareWindow).Square){resolve();return;}const timer=setTimeout(()=>{cleanup();reject(new Error("sdk timeout"));},REQUEST_TIMEOUT);const loaded=()=>{cleanup();resolve();},failed=()=>{cleanup();reject(new Error("sdk"));};const cleanup=()=>{clearTimeout(timer);script!.removeEventListener("load",loaded);script!.removeEventListener("error",failed);};script!.addEventListener("load",loaded,{once:true});script!.addEventListener("error",failed,{once:true});});if(!signal.active)throw new Error("unmounted");}
const wait=(ms:number,signal:AbortSignal)=>new Promise<void>((resolve,reject)=>{const timer=setTimeout(resolve,ms);signal.addEventListener("abort",()=>{clearTimeout(timer);reject(new Error("aborted"));},{once:true});});

export default function DowntownUCheckout({planId,eligibilityConfirmed,onLockChange}:{planId:DowntownUPlanId;eligibilityConfirmed:boolean;onLockChange?:(locked:boolean,planId:DowntownUPlanId)=>void}) {
 const initial=useRef<Recovery|null>(readRecovery());
 const [email,setEmail]=useState("");const [state,setState]=useState<State>(()=>initial.current?(initial.current.unresolved?"pending":"paid"):"loading");const [message,setMessage]=useState(()=>initial.current?(initial.current.unresolved?"We're recovering your existing payment attempt. Do not submit another payment.":"Payment confirmed. This checkout is locked."):"");
 const [locked,setLocked]=useState(Boolean(initial.current));const lockedRef=useRef(Boolean(initial.current));
 const card=useRef<Card|null>(null),key=useRef(initial.current?.idempotencyKey??newKey()),source=useRef<string|null>(null),snapshot=useRef<{planId:DowntownUPlanId;email:string}|null>(null),attempt=useRef<string|null>(initial.current?.attemptId??null),poll=useRef<AbortController|null>(null),emailInput=useRef<HTMLInputElement|null>(null);
 function setLock(value:boolean,lockedPlan:DowntownUPlanId=planId){lockedRef.current=value;setLocked(value);onLockChange?.(value,lockedPlan);}
 function definitiveFailure(){clearRecovery();attempt.current=null;snapshot.current=null;source.current=null;key.current=newKey();setLock(false);setState(card.current?"error":"loading");setMessage("Your card was declined. Check your card details and try again.");}
 function complete(result:{state:CheckoutState},recoveryPlan:DowntownUPlanId){if(result.state==="activated"||result.state==="paid"){persistRecovery({v:1,attemptId:attempt.current,idempotencyKey:key.current,planId:recoveryPlan,unresolved:false});setLock(true,recoveryPlan);setState("paid");setMessage(result.state==="activated"?"Payment confirmed and plan activated.":"Payment confirmed. Your plan is pending activation from Square's signed confirmation.");return true;}return false;}
 function showUnresolved(){if(source.current){setState("error");setMessage("We're still confirming this payment. Use Resume same payment attempt; it cannot create a new charge.");}else{setState("pending");setMessage("We're still confirming this payment. Do not submit another payment. Please contact Proper Cuisine if this does not resolve.");}}
 async function pollStatus(attemptId:string,recoveryPlan:DowntownUPlanId){const controller=new AbortController();poll.current?.abort();poll.current=controller;try{for(const delay of [250,500,1000,2000,4000]){await wait(delay,controller.signal);const {response,data}=await requestJson(`/api/downtown-u/checkout?id=${encodeURIComponent(attemptId)}`,{method:"GET"},controller.signal);const result=parseStatus(data);if(!response.ok||!result)throw new Error("status");if(complete(result,recoveryPlan))return;if(result.state==="failed"){definitiveFailure();return;}}showUnresolved();}catch{if(!controller.signal.aborted)showUnresolved();}finally{if(poll.current===controller)poll.current=null;}}
 // Recovery is intentionally read once per mount; callbacks operate on refs and the persisted plan.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const recovered=initial.current;if(recovered){setLock(true,recovered.planId);if(recovered.unresolved&&recovered.attemptId)void pollStatus(recovered.attemptId,recovered.planId);}},[]);
 useEffect(()=>{const alive={active:true};(async()=>{let instance:Card|null=null;try{if(!window.isSecureContext)throw new Error("insecure");const {response,data}=await requestJson("/api/downtown-u/checkout-config",{method:"GET"});const parsed=parseConfig(data);if(!response.ok||!parsed)throw new Error("config");await loadSquare(alive);const square=(window as SquareWindow).Square;if(!square||!alive.active)throw new Error("sdk");instance=await square.payments(parsed.applicationId,parsed.locationId).card();if(!alive.active){await instance.destroy();return;}await instance.attach("#downtown-u-card");if(!alive.active){await instance.destroy();return;}card.current=instance;instance=null;if(!lockedRef.current)setState("ready");}catch{if(instance)await instance.destroy().catch(()=>undefined);if(alive.active&&!lockedRef.current)setState("unavailable");}})();return()=>{alive.active=false;poll.current?.abort();poll.current=null;const current=card.current;card.current=null;if(current)void current.destroy().catch(()=>undefined);};},[]);
 async function pay(){if(!card.current||lockedRef.current&&!source.current||!eligibilityConfirmed||!emailInput.current?.checkValidity())return;const normalized=email.trim().toLowerCase();const currentSnapshot=snapshot.current??{planId,email:normalized};snapshot.current=currentSnapshot;const recovery:Recovery={v:1,attemptId:attempt.current,idempotencyKey:key.current,planId:currentSnapshot.planId,unresolved:true};if(!persistRecovery(recovery)){setState("error");setMessage("Checkout is unavailable because a safe recovery record could not be stored. No payment has been taken.");return;}setLock(true,currentSnapshot.planId);setState("submitting");setMessage("");try{let sourceId=source.current;if(!sourceId){const token=await card.current.tokenize();if(token.status!=="OK"||typeof token.token!=="string"||token.token.length<1){clearRecovery();snapshot.current=null;setLock(false);setState("error");setMessage("Check your card details and try again.");return;}sourceId=token.token;source.current=sourceId;}const {response,data}=await requestJson("/api/downtown-u/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planId:currentSnapshot.planId,sourceId,email:currentSnapshot.email,eligibilityConfirmed:true,idempotencyKey:key.current})});const result=parseCheckout(data);if(!result)throw new Error("response");attempt.current=result.attemptId;persistRecovery({...recovery,attemptId:result.attemptId});if(response.ok&&complete(result,currentSnapshot.planId))return;if(response.status===402&&result.state==="failed"){definitiveFailure();return;}if(response.status===202&&["started","order_created","payment_created","operator_review"].includes(result.state)){setState("pending");setMessage("We're confirming this payment. Do not submit another payment; check back shortly.");void pollStatus(result.attemptId,currentSnapshot.planId);return;}throw new Error("response");}catch{setState("error");setMessage("Checkout is temporarily unavailable. Retry only resumes this same payment attempt.");}}
 if(state==="unavailable")return <p role="alert" className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100">Embedded checkout is unavailable. No payment has been taken. Please contact Proper Cuisine for assistance.</p>;
 const mayRetry=state==="error"&&locked&&source.current!==null;
 const maySubmit=state==="ready"||(state==="error"&&!locked)||mayRetry;
 return <div className="space-y-4"><label className="block text-sm font-semibold text-cream/80">Student email<input ref={emailInput} type="email" autoComplete="email" required disabled={locked} value={email} onChange={event=>setEmail(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-black px-4 text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold disabled:opacity-60" /></label><div id="downtown-u-card" aria-label="Secure card details" aria-disabled={locked} className={`min-h-12 rounded-xl bg-white p-3 ${locked?"pointer-events-none opacity-60":""}`} />{state==="loading"&&<p role="status" className="text-sm text-cream/60">Loading secure card checkout…</p>}<button type="button" onClick={pay} disabled={!maySubmit||!eligibilityConfirmed||!email.trim()} className="min-h-14 w-full rounded-xl bg-gold px-5 font-bold text-jet-black disabled:opacity-50">{state==="submitting"?"Confirming payment…":mayRetry?"Resume same payment attempt":"Pay securely with Square"}</button>{message&&<p role={state==="error"?"alert":"status"} aria-live="polite" className="rounded-xl border border-white/10 p-4 text-sm text-cream/80">{message}</p>}<p className="text-center text-xs text-cream/40">Card details are securely hosted and tokenized by Square. Proper Cuisine never receives your card number.</p></div>;
}
