import { createHmac, timingSafeEqual } from "node:crypto";
import type { Pool, QueryResultRow } from "pg";
import { assertDowntownURuntimeIdentity, type Queryable } from "./postgres-runtime-identity";
import { withPostgresTransaction } from "./postgres-transaction";
import { PortalConflictError, PortalInsufficientCreditsError, PortalInvalidRequestError, PortalNotFoundError, PortalRateLimitError, type MealDefinition, type MealModifier, type PortalPrincipal, type PortalReservation, type StudentPortalStore } from "./student-portal";

interface PayloadRow extends QueryResultRow { payload: unknown }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const SESSION=/^[A-Za-z0-9_-]{43}$/;
function plain(value:unknown):Record<string,unknown>{if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return (()=>{throw new Error("invalid capability result")})();return value as Record<string,unknown>}
function exact(value:unknown,keys:readonly string[]):Record<string,unknown>{const x=plain(value);if(Object.keys(x).length!==keys.length||!keys.every(key=>Object.hasOwn(x,key)))throw new Error("invalid capability result");return x}
function iso(value:unknown):string{if(typeof value!=="string"||!Number.isFinite(Date.parse(value)))throw new Error("invalid capability result");return new Date(value).toISOString()}
function integer(value:unknown,min=0,max=Number.MAX_SAFE_INTEGER):number{if(typeof value!=="number"||!Number.isSafeInteger(value)||value<min||value>max)throw new Error("invalid capability result");return value}
function string(value:unknown,min=0,max=1024):string{if(typeof value!=="string"||value.length<min||value.length>max)throw new Error("invalid capability result");return value}
function nullableString(value:unknown,max:number):string|null{return value===null?null:string(value,1,max)}
function uuid(value:unknown):string{const out=string(value,36,36);if(!UUID.test(out))throw new Error("invalid capability result");return out}
function one(rows:PayloadRow[]):Record<string,unknown>{if(rows.length!==1)throw new Error("invalid capability result");return plain(rows[0].payload)}
function credential(principal:PortalPrincipal):[string,number,Buffer]{if(!SESSION.test(principal.sessionId)||!UUID.test(principal.studentId)||!Buffer.isBuffer(principal.digest)||principal.digest.length!==32)throw new Error("invalid portal principal");return[principal.sessionId,1,principal.digest]}
function cursorMac(principal:PortalPrincipal,endpoint:"purchases"|"reservations",payload:string):Buffer{return createHmac("sha256",principal.digest).update("downtown-u-portal-cursor\0v1\0").update(endpoint).update("\0").update(principal.studentId).update("\0").update(payload).digest()}
interface DecodedCursor{createdAt:string;id:string}
function decodeCursor(cursor:string|null,principal:PortalPrincipal,endpoint:"purchases"|"reservations"):DecodedCursor|null{if(cursor===null)return null;try{const parts=cursor.split(".");if(parts.length!==2||!/^[A-Za-z0-9_-]{1,342}$/.test(parts[0])||!/^[A-Za-z0-9_-]{43}$/.test(parts[1]))return null;const supplied=Buffer.from(parts[1],"base64url");const expected=cursorMac(principal,endpoint,parts[0]);if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))return null;const x=exact(JSON.parse(Buffer.from(parts[0],"base64url").toString("utf8")),["createdAt","id"]);return{createdAt:iso(x.createdAt),id:uuid(x.id)}}catch{return null}}
function encodeCursor(createdAt:unknown,id:unknown,principal:PortalPrincipal,endpoint:"purchases"|"reservations"):string{const payload=Buffer.from(JSON.stringify({createdAt:iso(createdAt),id:uuid(id)})).toString("base64url");return `${payload}.${cursorMac(principal,endpoint,payload).toString("base64url")}`}
function pgMessage(error:unknown):string{return typeof error==="object"&&error!==null&&"message" in error?String(error.message):""}
function mapped(error:unknown):never{const message=pgMessage(error);const code=typeof error==="object"&&error!==null&&"code" in error?String(error.code):"";if(message.includes("rate limited"))throw new PortalRateLimitError();if(message.includes("insufficient credits"))throw new PortalInsufficientCreditsError();if(code==="23505"||message.includes("idempotency conflict")||message.includes("not cancellable")||message.includes("expired reservation"))throw new PortalConflictError();if(message.includes("not found"))throw new PortalNotFoundError();if(message.includes("invalid request"))throw new PortalInvalidRequestError();throw error}
function modifiers(value:unknown):MealModifier[]{if(!Array.isArray(value)||value.length>10)throw new Error("invalid capability result");const seen=new Set<string>();return value.map(item=>{const x=exact(item,["id","name","creditDelta"]);const id=string(x.id,1,80);if(seen.has(id))throw new Error("invalid capability result");seen.add(id);return{id,name:string(x.name,1,120),creditDelta:integer(x.creditDelta,-19,20)}})}
function meal(value:unknown):MealDefinition{const x=exact(value,["id","name","baseCredits","modifiers"]);return{id:string(x.id,1,80),name:string(x.name,1,120),baseCredits:integer(x.baseCredits,1,20),modifiers:modifiers(x.modifiers)}}
function reservation(value:unknown,list=false):PortalReservation{const x=exact(value,list?["id","mealId","mealName","modifiers","credits","status","reservedAt","expiresAt","reversedAt","createdAt"]:["id","mealId","mealName","modifiers","credits","status","reservedAt","expiresAt","reversedAt"]);const status=string(x.status);if(!["reserved","redeemed","reversed"].includes(status))throw new Error("invalid capability result");return{id:uuid(x.id),mealId:string(x.mealId,1,80),mealName:string(x.mealName,1,120),modifiers:modifiers(x.modifiers),credits:integer(x.credits,1,40),status:status as PortalReservation["status"],reservedAt:iso(x.reservedAt),expiresAt:iso(x.expiresAt),...(x.reversedAt===null?{}:{reversedAt:iso(x.reversedAt)})}}

export class PostgresStudentPortalStore implements StudentPortalStore {
 constructor(private readonly pool:Pool,private readonly preflight:(q:Queryable)=>Promise<void>=assertDowntownURuntimeIdentity){}
 private async query(sql:string,params:unknown[]):Promise<PayloadRow[]>{try{return await withPostgresTransaction(this.pool,async client=>{await this.preflight(client);return(await client.query<PayloadRow>(sql,params)).rows})}catch(error){mapped(error)}}
 async me(principal:PortalPrincipal){const x=exact(one(await this.query("SELECT payload FROM public.downtown_u_student_me($1,$2::smallint,$3::bytea)",credential(principal))),["studentId","email","phone","eligibilityStatus","availableCredits","activePlan"]);if(uuid(x.studentId)!==principal.studentId||x.eligibilityStatus!=="approved")throw new Error("invalid capability result");let activePlan:null|Record<string,unknown>=null;if(x.activePlan!==null){const p=exact(x.activePlan,["planId","creditsGranted","priceCents","currency","status","paidAt"]);const status=string(p.status);if(!["paid","partially_refunded"].includes(status))throw new Error("invalid capability result");activePlan={planId:string(p.planId,1,40),creditsGranted:integer(p.creditsGranted,1),priceCents:integer(p.priceCents,1),currency:string(p.currency,3,3),status,paidAt:iso(p.paidAt)}}return{studentId:principal.studentId,email:nullableString(x.email,254),phone:nullableString(x.phone,16),eligibilityStatus:"approved",availableCredits:integer(x.availableCredits),activePlan}}
 async meals(principal:PortalPrincipal){const rows=await this.query("SELECT payload FROM public.downtown_u_student_meals($1,$2::smallint,$3::bytea)",credential(principal));if(rows.length>100)throw new Error("invalid capability result");return rows.map(row=>meal(row.payload))}
 async purchases(principal:PortalPrincipal,options={limit:25,cursor:null as string|null}){const cursor=decodeCursor(options.cursor,principal,"purchases");if(options.cursor!==null&&!cursor)throw new PortalInvalidRequestError();const rows=await this.query("SELECT payload FROM public.downtown_u_student_purchases($1,$2::smallint,$3::bytea,$4::integer,$5::timestamptz,$6::uuid)",[...credential(principal),options.limit+1,cursor?.createdAt??null,cursor?.id??null]);const more=rows.length>options.limit;const selected=rows.slice(0,options.limit);const items=selected.map(row=>{const x=exact(row.payload,["id","planId","creditsGranted","priceCents","currency","status","refundedCredits","paidAt","createdAt"]);const status=string(x.status);if(!["paid","partially_refunded","refunded"].includes(status))throw new Error("invalid capability result");return{id:uuid(x.id),planId:string(x.planId,1,40),creditsGranted:integer(x.creditsGranted,1),priceCents:integer(x.priceCents,1),currency:string(x.currency,3,3),status,refundedCredits:integer(x.refundedCredits),paidAt:iso(x.paidAt),createdAt:iso(x.createdAt)}});const last=selected.at(-1)?.payload;return{items,nextCursor:more&&last?encodeCursor(plain(last).createdAt,plain(last).id,principal,"purchases"):null}}
 async reservations(principal:PortalPrincipal,options={limit:25,cursor:null as string|null}){const cursor=decodeCursor(options.cursor,principal,"reservations");if(options.cursor!==null&&!cursor)throw new PortalInvalidRequestError();const rows=await this.query("SELECT payload FROM public.downtown_u_student_reservations($1,$2::smallint,$3::bytea,$4::integer,$5::timestamptz,$6::uuid)",[...credential(principal),options.limit+1,cursor?.createdAt??null,cursor?.id??null]);const more=rows.length>options.limit;const selected=rows.slice(0,options.limit);const items=selected.map(row=>reservation(row.payload,true));const last=selected.at(-1)?.payload;return{items,nextCursor:more&&last?encodeCursor(plain(last).createdAt,plain(last).id,principal,"reservations"):null}}
 async reserve(input:{principal:PortalPrincipal;mealId:string;modifierIds:string[];idempotencyKey:string}){return reservation(one(await this.query("SELECT payload FROM public.downtown_u_student_reserve($1,$2::smallint,$3::bytea,$4,$5::text[],$6)",[...credential(input.principal),input.mealId,input.modifierIds,input.idempotencyKey])))}
 async reverse(input:{principal:PortalPrincipal;reservationId:string;idempotencyKey:string}){return reservation(one(await this.query("SELECT payload FROM public.downtown_u_student_reverse($1,$2::smallint,$3::bytea,$4::uuid,$5)",[...credential(input.principal),input.reservationId,input.idempotencyKey])))}
}
